// Alien Planet Defense v14 - CONFIG
// ------------------------------------------------------------
// Main tuning file. Edit these values directly to rebalance the game.
// v14 has continuous enemy spawning, XP level-ups, workers + build times,
// RTS unit pathfinding, looping truck routes, and a crystal logistics economy.
// ------------------------------------------------------------
const CONFIG={
  GAME:{
    STARTING_CREDITS:450,
    STARTING_BASE_HP:300
  },

  WORLD:{
    WIDTH:3200,
    HEIGHT:2400,
    BASE_RADIUS:68,
    CAMERA_SPEED:760,
    BASE_BUILD_CLEARANCE:10,
    BASE_TERRAIN_CLEARANCE:190
  },

  // Each building under construction consumes one worker until finished.
  WORKERS:{COUNT:3},
  BUILD_TIME:{
    LASER:6.0,
    FLAME:5.0,
    BLOCKADE:3.0,
    SAFE_SPOT:3.5,
    MINE:8.0
  },

  // ENEMY_SPEED_MULTIPLIER=0.50 means all enemies move at half speed.
  DIRECTOR:{
    START_GRACE:4.0,
    START_INTERVAL:3.2,
    MIN_INTERVAL:0.55,
    INTERVAL_DROP_PER_MIN:0.22,
    BASE_CLUSTER:3,
    EXTRA_CLUSTER_PER_MIN:1,
    MAX_EXTRA_CLUSTER:8,
    ENEMY_SPEED_MULTIPLIER:0.50
  },

  XP:{START_TO_LEVEL:90,GROWTH:1.32},

  SOLDIER:{COST:35,RANGE:215,MEMBERS:6,FIRE_INTERVAL:0.48,DAMAGE:1.45,BULLET_SPEED:740,MOVE_SPEED:165,HP:155},
  TRUCK:{COST:65,MOVE_SPEED:185,HP:130,CAPACITY:35,PICKUP_RANGE:58,UNLOAD_RANGE:120},

  LASER:{COST:75,RANGE:400,FIRE_INTERVAL:1.42,DAMAGE:72,BULLET_SPEED:1050,HP:190},
  FLAME:{COST:60,RANGE:160,FIRE_INTERVAL:0.11,BURN_TICK_DAMAGE:4.2,BURN_TICK_INTERVAL:0.28,BURN_DURATION:3.1,HP:170},
  BLOCKADE:{COST:22,HP:420,WIDTH:78,HEIGHT:22},
  SAFE_SPOT:{COST:45,RADIUS:31,PLACEMENT_CLEARANCE:50,HP:180},

  CRYSTALS:{
    DEPOT_COUNT:12,
    DEPOT_RADIUS:30,
    DEPOT_BASE_STOCK:500,
    DEPOT_BASE_CLEARANCE:300,
    DEPOT_SEPARATION:280,
    MINE_COST:85,
    MINE_HP:170,
    MINE_PLACEMENT_RANGE:140,
    MINE_RATE:3.0,
    MINE_STORAGE:80,
    MONEY_PER_CRYSTAL:2
  },

  PATHFINDING:{CELL_SIZE:48,MAX_VISITED:7000},

  SWARM:{BASE_HP:3.5,HP_PER_LEVEL:0.35,BASE_SPEED:78,SPEED_PER_LEVEL:1.0,RADIUS:4.7,BASE_DAMAGE:1,XP:4},
  RUNNER:{BASE_HP:5.5,HP_PER_LEVEL:0.5,BASE_SPEED:108,SPEED_PER_LEVEL:1.3,RADIUS:6.2,BASE_DAMAGE:2,XP:6},
  BRUTE:{BASE_HP:34,HP_PER_LEVEL:3.2,BASE_SPEED:36,SPEED_PER_LEVEL:0.5,RADIUS:14,BASE_DAMAGE:8,XP:18},
  RANGED_ALIEN:{SPAWN_CHANCE:0.03,BASE_HP:18,HP_PER_LEVEL:1.5,BASE_SPEED:40,SPEED_PER_LEVEL:0.4,RADIUS:10,BASE_DAMAGE:3,XP:11,ATTACK_RANGE:195,SHOT_DAMAGE:7,FIRE_INTERVAL:1.8,PROJECTILE_SPEED:285},

  TOWER_DURABILITY:{MELEE_ATTACK_RANGE:20,MELEE_AGGRO_RANGE:105,MELEE_DAMAGE_MULTIPLIER:1.0},
  TERRAIN:{MIN_OBSTACLES:38,EXTRA_OBSTACLES_RANDOM:16,MIN_RADIUS:24,MAX_RADIUS:50,BUILD_CLEARANCE:5,ENEMY_STEER_STRENGTH:250},
  CARD_RARITY:{COMMON:58,UNCOMMON:28,RARE:11,EPIC:3}
};
