canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);const p=worldFromEvent(e);pointer={id:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY,drag:false,type:e.pointerType,world:p};});
canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.lastX,dy=e.clientY-pointer.lastY;if(Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)>8)pointer.drag=true;if(pointer.type==='touch'&&pointer.drag){const r=canvas.getBoundingClientRect();state.camera.x-=dx*W/r.width;state.camera.y-=dy*H/r.height;clampCamera();}pointer.lastX=e.clientX;pointer.lastY=e.clientY;});
canvas.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;const wasDrag=pointer.drag,p=worldFromEvent(e);pointer=null;if(!wasDrag)handleTap(p.x,p.y,p.sx,p.sy);});
canvas.addEventListener('contextmenu',e=>e.preventDefault());

function unitAt(x,y){let best=null,bd=32;for(const u of state.units){const d=Math.hypot(x-u.x,y-u.y);if(d<bd){best=u;bd=d;}}return best;}
function selectedCancelHit(x,y){const u=state.selectedUnit;if(!u)return false;return Math.hypot(x-(u.x+34),y-(u.y-34))<18;}
function handleTap(x,y){if(state.gameOver||state.choosing)return;if(selectedCancelHit(x,y)){state.selectedUnit=null;els.message.textContent='Unit selection cancelled.';updateHud();return;}const clicked=unitAt(x,y);if(clicked){state.selectedUnit=clicked;els.message.textContent=`${clicked.type==='truck'?'Truck':'Fire Squad'} selected. Tap a destination.`;updateHud();return;}if(state.selectedUnit){if(pointBlocked(x,y,20)){els.message.textContent='That destination is blocked.';return;}state.selectedUnit.moveTarget={x,y};els.message.textContent='Move order issued.';return;}placeBuild(x,y);}
function spend(cost){if(state.debug.unlimitedCash)return true;if(state.credits<cost)return false;state.credits-=cost;return true;}
function placeBuild(x,y){const def=BUILD[buildType];if(!def)return;if(pointBlocked(x,y,buildType==='blockade'?28:22)){els.message.textContent='You cannot build there.';return;}if(!spend(def.cost)){els.message.textContent=`Need ${def.cost} credits.`;return;}
 if(buildType==='soldier'){state.units.push({id:'u'+Date.now()+Math.random(),type:'soldier',x,y,hp:CONFIG.SOLDIER.HP,maxHp:CONFIG.SOLDIER.HP,range:CONFIG.SOLDIER.RANGE,moveTarget:null,cooldowns:Array(CONFIG.SOLDIER.MEMBERS).fill(0).map(()=>Math.random()*.3)});}
 else if(buildType==='truck'){state.units.push({id:'u'+Date.now()+Math.random(),type:'truck',x,y,hp:CONFIG.TRUCK.HP*state.mods.truckHp,maxHp:CONFIG.TRUCK.HP*state.mods.truckHp,moveTarget:null,cargo:0});}
 else if(buildType==='safespot'){if(state.safeSpots.some(s=>Math.hypot(x-s.x,y-s.y)<CONFIG.SAFE_SPOT.PLACEMENT_CLEARANCE)){refund(def.cost);els.message.textContent='Safe Spots are too close together.';return;}state.safeSpots.push({id:'s'+Date.now()+Math.random(),x,y,occupied:false});}
 else if(buildType==='mine'){const depot=state.depots.find(d=>!d.mineId&&Math.hypot(x-d.x,y-d.y)<=CONFIG.CRYSTALS.MINE_PLACEMENT_RANGE);if(!depot){refund(def.cost);els.message.textContent='Crystal Mines must be placed close to an unused crystal depot.';return;}const mine={id:'m'+Date.now()+Math.random(),type:'mine',x,y,hp:CONFIG.CRYSTALS.MINE_HP,maxHp:CONFIG.CRYSTALS.MINE_HP,stored:0,depotId:depot.id};state.structures.push(mine);depot.mineId=mine.id;}
 else{let px=x,py=y,protectedTower=false,safeSpotId=null;const pad=state.safeSpots.find(s=>!s.occupied&&Math.hypot(x-s.x,y-s.y)<=CONFIG.SAFE_SPOT.RADIUS);if(pad&&buildType!=='blockade'){px=pad.x;py=pad.y;pad.occupied=true;protectedTower=true;safeSpotId=pad.id;}const hp=buildType==='laser'?CONFIG.LASER.HP:buildType==='flame'?CONFIG.FLAME.HP:CONFIG.BLOCKADE.HP;state.structures.push({id:'t'+Date.now()+Math.random(),type:buildType,x:px,y:py,hp,maxHp:hp,protected:protectedTower,safeSpotId,cool:Math.random()*.2,w:CONFIG.BLOCKADE.WIDTH,h:CONFIG.BLOCKADE.HEIGHT});}
 updateHud();}
function refund(cost){if(!state.debug.unlimitedCash)state.credits+=cost;}

function spawnEnemy(){const minute=Math.floor(state.elapsed/60),level=minute+1,edge=Math.floor(Math.random()*4),m=30;let x,y;if(edge===0){x=m+Math.random()*(WORLD_W-2*m);y=m}else if(edge===1){x=WORLD_W-m;y=m+Math.random()*(WORLD_H-2*m)}else if(edge===2){x=m+Math.random()*(WORLD_W-2*m);y=WORLD_H-m}else{x=m;y=m+Math.random()*(WORLD_H-2*m)};const r=Math.random();let type=r<CONFIG.RANGED_ALIEN.SPAWN_CHANCE?'spitter':r<.68?'swarm':r<.93?'runner':'brute';const c=type==='swarm'?CONFIG.SWARM:type==='runner'?CONFIG.RUNNER:type==='brute'?CONFIG.BRUTE:CONFIG.RANGED_ALIEN;state.enemies.push({type,x,y,hp:c.BASE_HP+level*c.HP_PER_LEVEL,maxHp:c.BASE_HP+level*c.HP_PER_LEVEL,speed:c.BASE_SPEED+level*c.SPEED_PER_LEVEL,r:c.RADIUS,damage:c.BASE_DAMAGE,xp:c.XP,burn:0,burnTick:0,animOffset:Math.random()*100,rangeCooldown:Math.random()*(CONFIG.RANGED_ALIEN.FIRE_INTERVAL||1)});}
function updateDirector(dt){state.spawnTimer-=dt;if(state.spawnTimer>0)return;const minute=Math.floor(state.elapsed/60),count=CONFIG.DIRECTOR.BASE_CLUSTER+Math.min(CONFIG.DIRECTOR.MAX_EXTRA_CLUSTER,minute*CONFIG.DIRECTOR.EXTRA_CLUSTER_PER_MIN);for(let i=0;i<count;i++)spawnEnemy();state.spawnTimer=Math.max(CONFIG.DIRECTOR.MIN_INTERVAL,CONFIG.DIRECTOR.START_INTERVAL-minute*CONFIG.DIRECTOR.INTERVAL_DROP_PER_MIN);}

function gainXp(amount){state.xp+=amount;if(!state.choosing&&state.xp>=state.nextXp){state.xp-=state.nextXp;state.xpLevel++;state.nextXp=Math.round(state.nextXp*CONFIG.XP.GROWTH);showCards();}}
function hitEnemy(e,dmg){e.hp-=dmg;if(e.hp<=0){const i=state.enemies.indexOf(e);if(i>=0)state.enemies.splice(i,1);gainXp(e.xp);for(let k=0;k<(e.type==='brute'?9:4);k++)state.particles.push({x:e.x,y:e.y,vx:(Math.random()-.5)*100,vy:(Math.random()-.5)*100,life:.45});}}
function weightedRarity(){const x=Math.random()*100;let sum=0;for(const n of ['common','uncommon','rare','epic']){sum+=RARITIES[n];if(x<sum)return n;}return 'common';}
function showCards(){state.choosing=true;const choices=[],used=new Set();while(choices.length<3){const rar=weightedRarity(),pool=UPGRADES.filter(u=>u.rarity===rar),u=pool[Math.floor(Math.random()*pool.length)]||UPGRADES[0];if(!used.has(u.name)){used.add(u.name);choices.push(u);}}els.cards.innerHTML='';for(const u of choices){const b=document.createElement('button');b.className=`upgradeCard ${u.rarity}`;b.innerHTML=`<span class="rarity">${u.rarity.toUpperCase()}</span><h3>${u.name}</h3><p>${u.desc}</p><span class="tag">${u.tag}</span>`;b.onclick=()=>{u.apply(state);state.choosing=false;els.overlay.classList.add('hidden');els.message.textContent=`Upgrade acquired: ${u.name}`;if(state.xp>=state.nextXp)gainXp(0);};els.cards.appendChild(b);}els.overlay.classList.remove('hidden');}
