function findTarget(x,y,range){let best=null,bd=Infinity;for(const e of state.enemies){const d=Math.hypot(e.x-x,e.y-y);if(d<range&&d<bd){best=e;bd=d;}}return best;}
function shoot(x,y,e,type,dmg,speed,jitter=0){const a=Math.atan2(e.y-y,e.x-x)+(Math.random()-.5)*jitter;state.bullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,dmg,life:2,type});}
function updateUnits(dt){for(const u of state.units){if(u.moveTarget){const dx=u.moveTarget.x-u.x,dy=u.moveTarget.y-u.y,d=Math.hypot(dx,dy);if(d<5){u.x=u.moveTarget.x;u.y=u.moveTarget.y;u.moveTarget=null;}else{const speed=(u.type==='truck'?CONFIG.TRUCK.MOVE_SPEED:CONFIG.SOLDIER.MOVE_SPEED)*state.mods.unitMove,step=Math.min(d,speed*dt),a=Math.atan2(dy,dx);let nx=u.x+Math.cos(a)*step,ny=u.y+Math.sin(a)*step;if(!pointBlocked(nx,ny,18)){u.x=nx;u.y=ny;}}}
 if(u.type==='soldier'){const count=CONFIG.SOLDIER.MEMBERS+state.mods.extraSoldiers;while(u.cooldowns.length<count)u.cooldowns.push(Math.random()*.2);for(let i=0;i<u.cooldowns.length;i++){u.cooldowns[i]-=dt;if(u.cooldowns[i]>0)continue;const target=findTarget(u.x,u.y,CONFIG.SOLDIER.RANGE);if(target){const off=SOLDIER_OFFSETS[i%6];shoot(u.x+off[0],u.y+off[1],target,'soldier',CONFIG.SOLDIER.DAMAGE*state.mods.soldierDamage,CONFIG.SOLDIER.BULLET_SPEED);u.cooldowns[i]=CONFIG.SOLDIER.FIRE_INTERVAL*state.mods.soldierRate;}}}
 if(u.type==='truck'){const cap=Math.round(CONFIG.TRUCK.CAPACITY*state.mods.truckCapacity);if(u.cargo<cap){let mine=null,bd=CONFIG.TRUCK.PICKUP_RANGE;for(const s of state.structures)if(s.type==='mine'&&s.stored>0){const d=Math.hypot(u.x-s.x,u.y-s.y);if(d<bd){mine=s;bd=d;}}if(mine){const take=Math.min(cap-u.cargo,mine.stored);u.cargo+=take;mine.stored-=take;}}
 if(u.cargo>0&&Math.hypot(u.x-BASE_X,u.y-BASE_Y)<BASE_RADIUS+CONFIG.TRUCK.UNLOAD_RANGE){const money=u.cargo*CONFIG.CRYSTALS.MONEY_PER_CRYSTAL*state.mods.crystalValue;if(!state.debug.unlimitedCash)state.credits+=money;u.cargo=0;els.message.textContent=`Truck delivered crystals: +${Math.round(money)} credits.`;}}
 }}
function updateMines(dt){for(const s of state.structures){if(s.type!=='mine')continue;const depot=state.depots.find(d=>d.id===s.depotId);if(!depot||depot.stock<=0)continue;const cap=CONFIG.CRYSTALS.MINE_STORAGE*state.mods.mineStorage,amount=Math.min(CONFIG.CRYSTALS.MINE_RATE*state.mods.mineRate*dt,depot.stock,cap-s.stored);if(amount>0){s.stored+=amount;depot.stock-=amount;}}}
function structureRange(s){return s.type==='laser'?CONFIG.LASER.RANGE:s.type==='flame'?CONFIG.FLAME.RANGE:0;}
function updateTowers(dt){for(const s of state.structures){if(s.type!=='laser'&&s.type!=='flame')continue;s.cool-=dt;if(s.cool>0)continue;const target=findTarget(s.x,s.y,structureRange(s));if(!target)continue;if(s.type==='laser'){shoot(s.x,s.y,target,'laser',CONFIG.LASER.DAMAGE*state.mods.laserDamage,CONFIG.LASER.BULLET_SPEED);s.cool=CONFIG.LASER.FIRE_INTERVAL*state.mods.laserRate;}else{target.burn=Math.max(target.burn,CONFIG.FLAME.BURN_DURATION*state.mods.burnDuration);target.burnTick=Math.min(target.burnTick,.01);s.cool=CONFIG.FLAME.FIRE_INTERVAL;}}}
function closestAttackTarget(e,maxRange,includeProtected){let best=null,bd=Infinity;for(const s of state.structures){if(!includeProtected&&s.protected)continue;const d=Math.hypot(e.x-s.x,e.y-s.y);if(d<maxRange&&d<bd){best=s;bd=d;}}for(const u of state.units){const d=Math.hypot(e.x-u.x,e.y-u.y);if(d<maxRange&&d<bd){best=u;bd=d;}}return best;}
function updateEnemies(dt){for(const e of [...state.enemies]){if(e.burn>0){e.burn-=dt;e.burnTick-=dt;if(e.burnTick<=0){hitEnemy(e,CONFIG.FLAME.BURN_TICK_DAMAGE*state.mods.flameDamage);e.burnTick=CONFIG.FLAME.BURN_TICK_INTERVAL;continue;}}let speed=e.speed,attacking=false;for(const o of state.terrain){const d=Math.hypot(e.x-o.x,e.y-o.y);if(d<o.r+e.r+30){const dx=e.x-o.x||1,dy=e.y-o.y||0,l=Math.hypot(dx,dy)||1;e.x+=dx/l*CONFIG.TERRAIN.ENEMY_STEER_STRENGTH*dt*.35;e.y+=dy/l*CONFIG.TERRAIN.ENEMY_STEER_STRENGTH*dt*.15;}}
 if(e.type==='spitter'){e.rangeCooldown-=dt;const t=closestAttackTarget(e,CONFIG.RANGED_ALIEN.ATTACK_RANGE,true);if(t){speed*=.2;if(e.rangeCooldown<=0){const dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy)||1;state.enemyBullets.push({x:e.x,y:e.y,vx:dx/d*CONFIG.RANGED_ALIEN.PROJECTILE_SPEED,vy:dy/d*CONFIG.RANGED_ALIEN.PROJECTILE_SPEED,dmg:CONFIG.RANGED_ALIEN.SHOT_DAMAGE,life:2.5,target:t});e.rangeCooldown=CONFIG.RANGED_ALIEN.FIRE_INTERVAL;}}}else{const t=closestAttackTarget(e,CONFIG.TOWER_DURABILITY.MELEE_ATTACK_RANGE+e.r+25,false);if(t){const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<CONFIG.TOWER_DURABILITY.MELEE_ATTACK_RANGE+e.r){t.hp-=e.damage*CONFIG.TOWER_DURABILITY.MELEE_DAMAGE_MULTIPLIER*dt;speed=0;attacking=true;}}}
 if(!attacking||speed>0){const dx=BASE_X-e.x,dy=BASE_Y-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*speed*dt;e.y+=dy/d*speed*dt;}if(Math.hypot(e.x-BASE_X,e.y-BASE_Y)<BASE_RADIUS+e.r){state.enemies.splice(state.enemies.indexOf(e),1);if(!state.debug.unlimitedLives)state.baseHp-=e.damage;}}
 state.units=state.units.filter(u=>{if(u.hp>0)return true;if(state.selectedUnit===u)state.selectedUnit=null;return false;});state.structures=state.structures.filter(s=>{if(s.hp>0)return true;if(s.type==='mine'){const d=state.depots.find(x=>x.id===s.depotId);if(d)d.mineId=null;}if(s.safeSpotId){const p=state.safeSpots.find(x=>x.id===s.safeSpotId);if(p)p.occupied=false;}return false;});}
function updateProjectiles(dt){for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0){state.bullets.splice(i,1);continue;}let hit=false;for(const e of state.enemies){if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+5){hitEnemy(e,b.dmg);hit=true;break;}}if(hit)state.bullets.splice(i,1);}for(let i=state.enemyBullets.length-1;i>=0;i--){const b=state.enemyBullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;const valid=state.units.includes(b.target)||state.structures.includes(b.target);if(!valid||b.life<=0){state.enemyBullets.splice(i,1);continue;}if(Math.hypot(b.x-b.target.x,b.y-b.target.y)<24){b.target.hp-=b.dmg;state.enemyBullets.splice(i,1);}}}

function update(dt){if(state.gameOver){updateCamera(dt);return;}updateCamera(dt);if(state.choosing)return;state.elapsed+=dt;updateDirector(dt);updateMines(dt);updateUnits(dt);updateTowers(dt);updateEnemies(dt);updateProjectiles(dt);for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)state.particles.splice(i,1);}if(state.debug.unlimitedLives)state.baseHp=state.maxBaseHp;if(state.baseHp<=0&&!state.debug.unlimitedLives){state.baseHp=0;state.gameOver=true;els.message.textContent='THE BASE HAS FALLEN — press RESTART.';}updateHud();}
