function drawBackdrop(){
 ctx.fillStyle='#10221b';ctx.fillRect(0,0,WORLD_W,WORLD_H);
 for(let i=0;i<540;i++){const x=(i*173+31)%WORLD_W,y=(i*97+19)%WORLD_H;ctx.fillStyle=i%4?'#234a37':'#59d49a';ctx.globalAlpha=i%4?.35:.1;ctx.fillRect(x,y,2+(i%3),2+(i%2));}
 ctx.globalAlpha=1;
 for(const o of state.terrain){if(o.kind==='rock'){ctx.fillStyle='#27302d';ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3b4943';ctx.beginPath();ctx.arc(o.x-o.r*.22,o.y-o.r*.24,o.r*.62,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle='#1f3431';ctx.beginPath();ctx.arc(o.x,o.y,o.r*.82,0,Math.PI*2);ctx.fill();ctx.fillStyle='#58dca9';ctx.globalAlpha=.68;ctx.beginPath();ctx.moveTo(o.x,o.y-o.r);ctx.lineTo(o.x-o.r*.35,o.y+o.r*.45);ctx.lineTo(o.x+o.r*.35,o.y+o.r*.45);ctx.closePath();ctx.fill();ctx.globalAlpha=1;}}
 for(const d of state.depots)drawDepot(d);
}
function drawDepot(d){ctx.save();ctx.translate(d.x,d.y);ctx.fillStyle='rgba(35,20,55,.78)';ctx.beginPath();ctx.arc(0,0,d.r+7,0,Math.PI*2);ctx.fill();for(let i=0;i<6;i++){const a=i*Math.PI/3,r=10+(i%2)*7;ctx.fillStyle=d.stock>0?'#b46cff':'#62556e';ctx.beginPath();ctx.moveTo(Math.cos(a)*r,Math.sin(a)*r-12);ctx.lineTo(Math.cos(a)*r-6,Math.sin(a)*r+8);ctx.lineTo(Math.cos(a)*r+6,Math.sin(a)*r+8);ctx.closePath();ctx.fill();}ctx.fillStyle='#e6c8ff';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(`${Math.ceil(d.stock)} crystal`,0,d.r+18);ctx.restore();}
function drawBase(){const ratio=Math.max(0,state.baseHp/state.maxBaseHp);ctx.save();ctx.translate(BASE_X,BASE_Y);ctx.fillStyle='#182b3d';ctx.beginPath();ctx.arc(0,0,BASE_RADIUS+10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#7895aa';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,BASE_RADIUS,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#263a4c';ctx.beginPath();ctx.arc(0,0,BASE_RADIUS-7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#7bd6e8';ctx.beginPath();ctx.arc(0,0,BASE_RADIUS*.35,0,Math.PI*2);ctx.fill();const y=-BASE_RADIUS-36,bw=160;ctx.fillStyle='#07111a';ctx.fillRect(-bw/2-7,y-20,bw+14,38);ctx.fillStyle='#eaf7ff';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(state.debug.unlimitedLives?'BASE ∞ HP':`BASE ${Math.ceil(state.baseHp)} / ${state.maxBaseHp}`,0,y-5);ctx.fillStyle='#111';ctx.fillRect(-bw/2,y+2,bw,10);ctx.fillStyle=ratio>.5?'#59d878':ratio>.25?'#f0c65a':'#ef6666';ctx.fillRect(-bw/2,y+2,bw*(state.debug.unlimitedLives?1:ratio),10);ctx.restore();}
function drawConstruction(s){const ratio=1-s.buildRemaining/s.buildTime;ctx.save();ctx.translate(s.x,s.y);ctx.strokeStyle='rgba(240,210,105,.9)';ctx.lineWidth=2;ctx.setLineDash([6,5]);ctx.strokeRect(-24,-20,48,40);ctx.setLineDash([]);ctx.fillStyle='rgba(15,22,28,.85)';ctx.fillRect(-28,24,56,12);ctx.fillStyle='#171717';ctx.fillRect(-25,27,50,6);ctx.fillStyle='#f4d36f';ctx.fillRect(-25,27,50*Math.max(0,Math.min(1,ratio)),6);ctx.fillStyle='#f8e9a8';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.fillText(`${Math.round(ratio*100)}%`,0,22);ctx.restore();}
function drawStructure(s){
 if(!s.built){drawConstruction(s);return;}
 ctx.save();ctx.translate(s.x,s.y);
 if(state.showReach&&(s.type==='laser'||s.type==='flame')){ctx.strokeStyle='rgba(255,255,255,.24)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,structureRange(s),0,Math.PI*2);ctx.stroke();}
 if(s.protected){ctx.strokeStyle='#72e6ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,31,0,Math.PI*2);ctx.stroke();}
 if(s.type==='laser'){ctx.fillStyle='#281d26';ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff5c67';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#ff7a83';ctx.fillRect(-4,-20,8,25);}
 else if(s.type==='flame'){ctx.fillStyle='#33231a';ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff8b32';ctx.fillRect(-5,-20,10,20);}
 else if(s.type==='blockade'){ctx.fillStyle='#263442';ctx.fillRect(-s.w/2,-s.h/2,s.w,s.h);ctx.strokeStyle='#8aa6ba';ctx.strokeRect(-s.w/2,-s.h/2,s.w,s.h);}
 else if(s.type==='mine'){ctx.fillStyle='#342947';ctx.fillRect(-22,-18,44,36);ctx.strokeStyle='#bf89ff';ctx.strokeRect(-22,-18,44,36);ctx.fillStyle='#9f63e8';ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(-10,-8);ctx.lineTo(10,-8);ctx.closePath();ctx.fill();ctx.fillStyle='#dec5ff';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(`${Math.floor(s.stored)}/${Math.round(CONFIG.CRYSTALS.MINE_STORAGE*state.mods.mineStorage)}`,0,30);}
 else if(s.type==='safespot'){ctx.fillStyle=s.occupied?'rgba(60,180,205,.28)':'rgba(60,220,245,.18)';ctx.strokeStyle=s.occupied?'#4eb6ce':'#72e6ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,CONFIG.SAFE_SPOT.RADIUS,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,CONFIG.SAFE_SPOT.RADIUS*.55,0,Math.PI*2);ctx.stroke();}
 if(s.hp<s.maxHp){ctx.fillStyle='#111';ctx.fillRect(-22,32,44,4);ctx.fillStyle='#ef6666';ctx.fillRect(-22,32,44*Math.max(0,s.hp/s.maxHp),4);}ctx.restore();
}
function drawRoute(u){if(u.type!=='truck'||!u.route||!u.route.length)return;ctx.save();ctx.strokeStyle=u.routeLoop?'rgba(210,145,255,.9)':'rgba(190,135,240,.55)';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(u.x,u.y);for(const p of u.route)ctx.lineTo(p.x,p.y);if(u.routeLoop&&u.route.length>1)ctx.lineTo(u.route[0].x,u.route[0].y);ctx.stroke();ctx.setLineDash([]);for(let i=0;i<u.route.length;i++){const p=u.route[i];ctx.fillStyle='#d6a4ff';ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17101f';ctx.font='bold 8px Arial';ctx.textAlign='center';ctx.fillText(String(i+1),p.x,p.y+3);}ctx.restore();}
function drawUnit(u){
 drawRoute(u);ctx.save();ctx.translate(u.x,u.y);
 if(u.path&&u.path.length){ctx.setLineDash([8,6]);ctx.strokeStyle='rgba(96,225,255,.8)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);for(const p of u.path)ctx.lineTo(p.x-u.x,p.y-u.y);ctx.stroke();ctx.setLineDash([]);}
 if(u.type==='soldier'){ctx.fillStyle=u.attachedTo?'#213a4a':'#172b3d';ctx.beginPath();ctx.arc(0,0,23,0,Math.PI*2);ctx.fill();const count=CONFIG.SOLDIER.MEMBERS+state.mods.extraSoldiers;for(let i=0;i<count;i++){const off=SOLDIER_OFFSETS[i%6];ctx.fillStyle='#c4d0d9';ctx.beginPath();ctx.arc(off[0],off[1]-4,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5d7387';ctx.fillRect(off[0]-3,off[1]-1,6,7);}if(u.attachedTo){ctx.strokeStyle='#d2a8ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,26,0,Math.PI*2);ctx.stroke();}}
 else{ctx.rotate(u.heading||0);ctx.fillStyle='#425b6d';ctx.fillRect(-18,-11,36,22);ctx.fillStyle='#7aa0b8';ctx.fillRect(-9,-13,18,26);ctx.fillStyle='#111';ctx.fillRect(-20,-14,6,8);ctx.fillRect(14,-14,6,8);ctx.fillRect(-20,6,6,8);ctx.fillRect(14,6,6,8);ctx.rotate(-(u.heading||0));ctx.fillStyle='#d2a8ff';ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.fillText(`${Math.floor(u.cargo)}/${Math.round(CONFIG.TRUCK.CAPACITY*state.mods.truckCapacity)}`,0,-22);}
 if(state.selectedUnit===u){ctx.strokeStyle='#ffe47b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.stroke();}
 if(u.hp<u.maxHp){ctx.fillStyle='#111';ctx.fillRect(-22,31,44,4);ctx.fillStyle='#ef6666';ctx.fillRect(-22,31,44*Math.max(0,u.hp/u.maxHp),4);}ctx.restore();
}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);if((e.type==='swarm'||e.type==='runner')&&SKITTER_MOVE.complete&&SKITTER_MOVE.naturalWidth){const frame=Math.floor(performance.now()/95+e.animOffset)%6,size=e.type==='runner'?34:27;ctx.drawImage(SKITTER_MOVE,frame*SKITTER_FRAME_SIZE,0,128,128,-size/2,-size/2,size,size);}else if(e.type==='brute'&&BRUTE_SPRITE.complete&&BRUTE_SPRITE.naturalWidth){ctx.drawImage(BRUTE_SPRITE,-36,-36,72,72);}else{ctx.fillStyle=e.type==='spitter'?'#8d72d8':e.type==='brute'?'#9a526b':'#75bb62';ctx.beginPath();ctx.arc(0,0,e.r,0,Math.PI*2);ctx.fill();}if(e.hp<e.maxHp){const w=e.type==='brute'?52:Math.max(18,e.r*2);ctx.fillStyle='#111';ctx.fillRect(-w/2,-e.r-8,w,3);ctx.fillStyle='#ef6666';ctx.fillRect(-w/2,-e.r-8,w*Math.max(0,e.hp/e.maxHp),3);}ctx.restore();}
function edgePoint(dx,dy,margin){const cx=W/2,cy=H/2;const scale=Math.min((W/2-margin)/Math.max(1,Math.abs(dx)),(H/2-margin)/Math.max(1,Math.abs(dy)));return{x:cx+dx*scale,y:cy+dy*scale};}
function drawOffscreenUnitIndicators(){for(const u of state.units){const sx=u.x-state.camera.x,sy=u.y-state.camera.y;if(sx>=0&&sx<=W&&sy>=0&&sy<=H)continue;const dx=sx-W/2,dy=sy-H/2,p=edgePoint(dx,dy,28),a=Math.atan2(dy,dx);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle=state.selectedUnit===u?'#ffe47b':u.type==='truck'?'#d2a8ff':'#7fe6ff';ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-7,-7);ctx.lineTo(-7,7);ctx.closePath();ctx.fill();ctx.restore();}}
function drawIncomingEnemyArrows(){const sectors=Array.from({length:12},()=>({count:0,dx:0,dy:0,dist:Infinity}));for(const e of state.enemies){const sx=e.x-state.camera.x,sy=e.y-state.camera.y;if(sx>=0&&sx<=W&&sy>=0&&sy<=H)continue;const dx=sx-W/2,dy=sy-H/2,a=Math.atan2(dy,dx),idx=(Math.floor(((a+Math.PI)/(Math.PI*2))*12)+12)%12,d=Math.hypot(dx,dy);const sec=sectors[idx];sec.count++;if(d<sec.dist){sec.dist=d;sec.dx=dx;sec.dy=dy;}}for(const sec of sectors){if(!sec.count)continue;const p=edgePoint(sec.dx,sec.dy,36),a=Math.atan2(sec.dy,sec.dx);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle='#ff4f55';ctx.strokeStyle='#450b0d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-8,-9);ctx.lineTo(-4,0);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText(sec.count,p.x,p.y+4);}}
function updateCancelButtonPosition(){const u=state.selectedUnit;if(!u){els.cancelUnit.classList.remove('visible');return;}const sx=u.x-state.camera.x,sy=u.y-state.camera.y;if(sx<0||sy<0||sx>W||sy>H){els.cancelUnit.classList.remove('visible');return;}const r=canvas.getBoundingClientRect(),shell=document.getElementById('canvasShell').getBoundingClientRect(),cssX=(r.left-shell.left)+sx*r.width/W,cssY=(r.top-shell.top)+sy*r.height/H;els.cancelUnit.style.left=`${cssX+26}px`;els.cancelUnit.style.top=`${cssY-30}px`;els.cancelUnit.classList.add('visible');}
function draw(){
 ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(-state.camera.x,-state.camera.y);drawBackdrop();drawBase();for(const s of state.structures)drawStructure(s);for(const u of state.units)drawUnit(u);for(const e of state.enemies)drawEnemy(e);for(const b of state.bullets){ctx.strokeStyle=b.type==='laser'?'#ff5967':'#fff0a0';ctx.lineWidth=b.type==='laser'?4:1.6;ctx.beginPath();ctx.moveTo(b.x-b.vx*.016,b.y-b.vy*.016);ctx.lineTo(b.x,b.y);ctx.stroke();}for(const b of state.enemyBullets){ctx.fillStyle='#9cff55';ctx.beginPath();ctx.arc(b.x,b.y,4,0,Math.PI*2);ctx.fill();}for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life/.45);ctx.fillStyle='#b9ff8a';ctx.fillRect(p.x,p.y,3,3);ctx.globalAlpha=1;}ctx.restore();
 drawOffscreenUnitIndicators();drawIncomingEnemyArrows();updateCancelButtonPosition();
 if(state.debug.unlimitedCash||state.debug.unlimitedLives){ctx.fillStyle='#7fe6ff';ctx.font='bold 13px Arial';ctx.textAlign='left';ctx.fillText(`DEBUG ${state.debug.unlimitedCash?'∞ CASH ':''}${state.debug.unlimitedLives?'∞ LIVES':''}`,14,H-14);}
 if(state.paused&&!state.gameOver){ctx.fillStyle='rgba(0,0,0,.36)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffe36b';ctx.font='bold 48px Arial';ctx.textAlign='center';ctx.fillText('PAUSED',W/2,80);ctx.font='16px Arial';ctx.fillText('Orders and building placements can still be queued',W/2,108);}
 if(state.gameOver){ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='bold 42px Arial';ctx.textAlign='center';ctx.fillText('BASE LOST',W/2,H/2);ctx.font='20px Arial';ctx.fillText('Press RESTART to begin a new run',W/2,H/2+38);}
}
function loop(now){const dt=Math.min(.033,(now-state.last)/1000);state.last=now;update(dt);draw();requestAnimationFrame(loop);}reset();requestAnimationFrame(loop);
