// Alien Planet Defense v43
// Consolidated gameplay repair: authoritative movable-unit purchasing, Rifleman
// combat, bunker removal, and zoom-stable fog tied to the exact world transform.
const V43_TITLE='Alien Planet Defense v43';document.title=V43_TITLE;window.addEventListener('load',()=>{document.title=V43_TITLE;},{once:true});
(function installV43Repair(){
const FOG_CELL=96,FOG_COLS=Math.ceil(WORLD_W/FOG_CELL),FOG_ROWS=Math.ceil(WORLD_H/FOG_CELL),fogCanvas=document.createElement('canvas');fogCanvas.width=W;fogCanvas.height=H;const fogCtx=fogCanvas.getContext('2d'),AIR_ROLES=new Set(['combatdrone','combatship']);
const role=u=>{try{return typeof unitRole==='function'?unitRole(u):(u?.role||u?.type)}catch{return u?.role||u?.type}},active=u=>!!u&&(Number(u.hp)||0)>0&&!u.transportedIn&&!u.garrisonedIn,rifle=u=>!!u&&u.type==='soldier'&&role(u)==='rifleman';
function removeBunkers(){document.querySelectorAll('.buildBtn[data-type="bunker"]').forEach(b=>b.remove());if(typeof BUILD==='object'&&BUILD)delete BUILD.bunker;const ids=new Set((state.structures||[]).filter(s=>s.type==='bunker').map(s=>s.id));for(const u of state.units||[])if(u.garrisonedIn&&ids.has(u.garrisonedIn)){u.garrisonedIn=null;u.path=[];u.moveTarget=null}state.structures=(state.structures||[]).filter(s=>s.type!=='bunker');if(state.selectedTower?.type==='bunker')state.selectedTower=null;if(state.selectedStorageBuilding?.type==='bunker')state.selectedStorageBuilding=null;for(const box of document.querySelectorAll('#guidePanel .guide-box'))if(/bunker/i.test(box.querySelector('b')?.textContent||''))box.remove();if(typeof garrisonBtn!=='undefined'&&garrisonBtn)garrisonBtn.style.display='none';if(typeof ungarrisonBtn!=='undefined'&&ungarrisonBtn)ungarrisonBtn.style.display='none'}removeBunkers();
const placeBuild0=placeBuild;placeBuild=function(x,y){if(buildType==='bunker'){buildType=null;if(els?.message)els.message.textContent='Bunkers have been removed.';return false}return placeBuild0(x,y)};
const updateUnitActions0=updateUnitActions;updateUnitActions=function(){updateUnitActions0();if(typeof garrisonBtn!=='undefined'&&garrisonBtn)garrisonBtn.style.display='none';if(typeof ungarrisonBtn!=='undefined'&&ungarrisonBtn)ungarrisonBtn.style.display='none'};
function unitCfg(r,air=false){try{if(typeof roleConfig==='function'){const c=roleConfig({type:air?'airunit':'soldier',role:r});if(c)return c}}catch{}if(r==='rifleman')return CONFIG.SOLDIER;const d={heavygunner:CONFIG.HEAVY_GUNNER,rocketeer:CONFIG.ROCKETEER,medic:CONFIG.MEDIC,engineer:CONFIG.ENGINEER,scout:CONFIG.SCOUT,sniper:CONFIG.SNIPER,flametrooper:CONFIG.FLAME_TROOPER,spotter:CONFIG.SPOTTER,minelayer:CONFIG.MINE_LAYER,mech:CONFIG.MECH,combatdrone:CONFIG.COMBAT_DRONE,combatship:CONFIG.COMBAT_SHIP,tank:CONFIG.TANK,mobileartillery:CONFIG.MOBILE_ARTILLERY,repairvehicle:CONFIG.REPAIR_VEHICLE,platoon:CONFIG.PLATOON,apc:CONFIG.APC};return d[r]||CONFIG.SOLDIER}
function spawnPoint(radius,air=false){const r=Math.max(12,Number(radius)||22);for(let ring=0;ring<12;ring++){const dist=BASE_RADIUS+r+22+ring*34;for(let i=0;i<48;i++){const a=i/48*Math.PI*2+ring*.19,x=BASE_X+Math.cos(a)*dist,y=BASE_Y+Math.sin(a)*dist;if(x<r+8||y<r+8||x>WORLD_W-r-8||y>WORLD_H-r-8)continue;if(air)return{x,y};let blocked=false;try{if(typeof pointBlockedByTerrain==='function'&&pointBlockedByTerrain(x,y,r*.45))blocked=true}catch{}if(blocked)continue;for(const s of state.structures||[]){if(s.type==='bunker')continue;if(s.type==='wall'&&typeof pointSegmentDistance==='function'){const t=typeof wallThickness==='function'?wallThickness(s):14;if(pointSegmentDistance(x,y,s.x1,s.y1,s.x2,s.y2)<r+t/2+5){blocked=true;break}}else if(Number.isFinite(s.x)&&Number.isFinite(s.y)){let sr=28;try{if(typeof structureRadius==='function')sr=structureRadius(s)}catch{}if(Math.hypot(x-s.x,y-s.y)<r+sr+5){blocked=true;break}}}if(!blocked)return{x,y}}}return{x:Math.max(r+8,Math.min(WORLD_W-r-8,BASE_X+BASE_RADIUS+r+44)),y:BASE_Y}}
function createUnit(type,p){if(type==='truck'){const hp=(Number(CONFIG.TRUCK.HP)||1)*(Number(state.mods?.truckHp)||1);return{id:'u'+Date.now()+Math.random(),type:'truck',x:p.x,y:p.y,hp,maxHp:hp,moveTarget:null,path:[],heading:0,cargo:0,cargoType:null,route:[],routeIndex:0,routeLoop:false,routeActive:false,routeWaiting:false,routePendingStart:false,platoonId:null,platoonSlot:0}}const r=type==='soldier'?'rifleman':type,air=AIR_ROLES.has(r),cfg=unitCfg(r,air)||{},hp=Number(cfg.HP)||Number(CONFIG.SOLDIER.HP)||1,members=Math.max(1,Number(cfg.MEMBERS)||Number(cfg.BARRELS)||1),u={id:'u'+Date.now()+Math.random(),type:air?'airunit':'soldier',role:r,x:p.x,y:p.y,hp,maxHp:hp,moveTarget:null,path:[],heading:0,attachedTo:null,attachSlot:0,garrisonedIn:null,cooldowns:Array.from({length:members},()=>Math.random()*.22),platoonId:null,platoonSlot:0,repairFxCooldown:0,healFxCooldown:0};if(r==='apc')u.passengerId=null;return u}
function purchaseUnit(type){const def=BUILD?.[type];if(!def||def.kind!=='unit')return false;if(type==='combatship'&&(state.units||[]).some(u=>role(u)==='combatship'&&u.hp>0)){if(els?.message)els.message.textContent='Only one Combat Ship can be active at a time.';return false}const cost=Math.max(0,Number(def.cost)||0),free=!!state.debug?.unlimitedCash;if(!free&&(Number(state.credits)||0)<cost){if(els?.message)els.message.textContent=`Need ${cost} gold for ${def.label}.`;if(typeof updateHud==='function')updateHud();return false}if(!free)state.credits-=cost;let u;try{const r=type==='soldier'?'rifleman':type,p=spawnPoint(def.radius,AIR_ROLES.has(r));u=createUnit(type,p);if(!u||!Number.isFinite(u.x)||!Number.isFinite(u.y)||!Number.isFinite(u.hp))throw new Error('invalid unit object');state.units.push(u)}catch(err){if(!free)state.credits+=cost;console.error('v43 unit deployment failed',type,err);if(els?.message)els.message.textContent=`Could not deploy ${def.label}. Purchase refunded.`;if(typeof updateHud==='function')updateHud();return false}buildType=null;state.routeEditing=false;state.attachMode=false;state.platoonAttachMode=false;state.v40MedicAttachMode=false;state.v40ApcAttachMode=false;state.selectedUnit=u;if('selectedTower'in state)state.selectedTower=null;if('selectedStorageBuilding'in state)state.selectedStorageBuilding=null;if(typeof updateTowerPanel==='function')updateTowerPanel();let name=def.label;try{if(typeof unitDisplayName==='function')name=unitDisplayName(u)||name}catch{}if(els?.message)els.message.textContent=`${name} deployed from the base.`;if(typeof updateHud==='function')updateHud();return true}
function installUnitButtons(){const menu=document.getElementById('unitsMenu');if(!menu)return;for(const oldBtn of [...menu.querySelectorAll('.buildBtn[data-type]')]){const type=oldBtn.dataset.type,def=BUILD?.[type];if(!def||def.kind!=='unit')continue;const btn=oldBtn.cloneNode(true);btn.type='button';btn.disabled=false;btn.classList.remove('selected');btn.onclick=e=>{e.preventDefault();e.stopPropagation();if(typeof resetWallPath==='function')try{resetWallPath()}catch{}const ok=purchaseUnit(type);if(ok&&typeof closeCommandMenu==='function')setTimeout(closeCommandMenu,0)};btn.onpointerdown=e=>e.stopPropagation();btn.onpointerup=e=>e.stopPropagation();oldBtn.replaceWith(btn)}}installUnitButtons();try{spawnUnitAtBase=purchaseUnit}catch{}
function rifleTarget(u){if(!active(u))return null;const cfg=unitCfg('rifleman')||CONFIG.SOLDIER,range=Number(cfg.RANGE)||CONFIG.SOLDIER.RANGE;let best=null,bd=range;for(const e of state.enemies||[]){if(!e||e.hp<=0)continue;try{if(typeof enemyTargetableFrom==='function'&&!enemyTargetableFrom(e,u.x,u.y))continue}catch{}const d=Math.hypot(e.x-u.x,e.y-u.y);if(d<=bd){best=e;bd=d}}return best}
function fireRifleBullet(x,y,target,damage,speed){const a=Math.atan2(target.y-y,target.x-x)+(Math.random()-.5)*.018;state.bullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,dmg:damage,life:2.2,type:'soldier'})}
const combat0=updateUnitCombat;updateUnitCombat=function(dt){const rifles=(state.units||[]).filter(u=>rifle(u)&&active(u)),parked=[];for(const u of rifles){parked.push([u,u.cooldowns]);const cfg=unitCfg('rifleman')||CONFIG.SOLDIER,n=Math.max(1,(Number(cfg.MEMBERS)||CONFIG.SOLDIER.MEMBERS||1)+(Number(state.mods?.extraSoldiers)||0));u.cooldowns=Array(n).fill(1e9)}try{combat0(dt)}catch(err){if(!state.v43LegacyCombatError){state.v43LegacyCombatError=String(err?.stack||err);console.error('v43: inherited non-rifle combat threw; Rifleman combat continues',err)}}finally{for(const [u,c] of parked)u.cooldowns=c}for(const u of rifles){if(!state.units.includes(u)||!active(u))continue;const cfg=unitCfg('rifleman')||CONFIG.SOLDIER,n=Math.max(1,(Number(cfg.MEMBERS)||CONFIG.SOLDIER.MEMBERS||1)+(Number(state.mods?.extraSoldiers)||0));if(!Array.isArray(u.v43RifleCooldowns))u.v43RifleCooldowns=Array.from({length:n},()=>Math.random()*.14);while(u.v43RifleCooldowns.length<n)u.v43RifleCooldowns.push(Math.random()*.14);if(u.v43RifleCooldowns.length>n)u.v43RifleCooldowns.length=n;const target=rifleTarget(u);for(let i=0;i<n;i++){u.v43RifleCooldowns[i]=(Number(u.v43RifleCooldowns[i])||0)-dt;if(u.v43RifleCooldowns[i]>0||!target)continue;const offsets=(typeof SOLDIER_OFFSETS!=='undefined'&&SOLDIER_OFFSETS?.length)?SOLDIER_OFFSETS:[[0,0]],off=offsets[i%offsets.length]||[0,0],damage=(Number(cfg.DAMAGE)||CONFIG.SOLDIER.DAMAGE)*(Number(state.mods?.soldierDamage)||1),speed=Number(cfg.BULLET_SPEED)||CONFIG.SOLDIER.BULLET_SPEED;fireRifleBullet(u.x+off[0],u.y+off[1],target,damage,speed);u.heading=Math.atan2(target.y-u.y,target.x-u.x);u.v43FiringUntil=performance.now()+170;u.v43RifleCooldowns[i]=(Number(cfg.FIRE_INTERVAL)||CONFIG.SOLDIER.FIRE_INTERVAL)*(Number(state.mods?.soldierRate)||1)*(.94+Math.random()*.12)}}};try{v35RiflemanTarget=rifleTarget}catch{}
function unitVision(u){const cfg=unitCfg(role(u),u.type==='airunit')||{},r=role(u);if(r==='scout')return 460;if(r==='spotter')return 440;if(r==='sniper')return 520;if(u.type==='airunit'||(typeof isFlyingUnit==='function'&&isFlyingUnit(u)))return 350;return Math.max(250,(Number(cfg.RANGE)||0)+65,Number(cfg.DETECT_RANGE)||0,Number(cfg.SPOT_RANGE)||0)}
function structureVision(s){if(!s?.built||s.hp<=0||s.type==='wall'||s.type==='bunker')return 0;try{if(typeof isUpgradeableTower==='function'&&isUpgradeableTower(s))return Math.max(265,(towerStats(s)?.range||0)+55)}catch{}if(s.type==='landingpad')return 330;if(s.type==='refinery')return 275;if(s.type==='mine'||s.type==='oremine')return 210;return 225}
function explored(){if(state.v43FogExplored instanceof Uint8Array&&state.v43FogExplored.length===FOG_COLS*FOG_ROWS)return state.v43FogExplored;const prior=[state.v42FogExplored,state.v37FogExplored,state.v36FogExplored,state.fogExplored].find(a=>a instanceof Uint8Array&&a.length===FOG_COLS*FOG_ROWS);state.v43FogExplored=prior?new Uint8Array(prior):new Uint8Array(FOG_COLS*FOG_ROWS);return state.v43FogExplored}
function refreshVision(){const ex=explored(),sources=[{x:BASE_X,y:BASE_Y,r:390,kind:'base',id:'base'}];for(const u of state.units||[])if(active(u))sources.push({x:u.x,y:u.y,r:unitVision(u),kind:'unit',id:u.id});for(const s of state.structures||[]){const r=structureVision(s);if(r>0)sources.push({x:s.x,y:s.y,r,kind:'structure',id:s.id})}state.v43VisionSources=sources;state.v42VisionSources=sources;state.v37VisionSources=sources;state.v36VisionSources=sources;state.v32VisionSources=sources;for(const v of sources){const c0=Math.max(0,Math.floor((v.x-v.r)/FOG_CELL)),c1=Math.min(FOG_COLS-1,Math.floor((v.x+v.r)/FOG_CELL)),r0=Math.max(0,Math.floor((v.y-v.r)/FOG_CELL)),r1=Math.min(FOG_ROWS-1,Math.floor((v.y+v.r)/FOG_CELL));for(let gy=r0;gy<=r1;gy++)for(let gx=c0;gx<=c1;gx++){const cx=gx*FOG_CELL+FOG_CELL/2,cy=gy*FOG_CELL+FOG_CELL/2;if(Math.hypot(cx-v.x,cy-v.y)<=v.r+FOG_CELL*.72)ex[gy*FOG_COLS+gx]=1}}}
function pointVisible(x,y){for(const v of state.v43VisionSources||[])if(Math.hypot(x-v.x,y-v.y)<=v.r)return true;return false}try{refreshFogSourcesV32=refreshVision}catch{}try{pointVisibleV32=pointVisible}catch{}try{drawFogOverlayV32=function(){}}catch{}
let frameMatrix=null;function snapshotMatrix(){if(typeof ctx.getTransform==='function'){const m=ctx.getTransform();return{a:m.a,b:m.b,c:m.c,d:m.d,e:m.e,f:m.f}}const z=Math.max(Number(CONFIG.WORLD.MIN_ZOOM)||.18,Math.min(Number(CONFIG.WORLD.MAX_ZOOM)||1.35,Number(state.camera?.zoom)||1));return{a:z,b:0,c:0,d:z,e:-state.camera.x*z,f:-state.camera.y*z}}function scaleOf(m){return Math.max(.0001,(Math.hypot(m.a,m.b)+Math.hypot(m.c,m.d))/2)}function inversePoint(m,sx,sy){const det=m.a*m.d-m.b*m.c;if(Math.abs(det)<1e-9)return{x:state.camera.x,y:state.camera.y};const x=sx-m.e,y=sy-m.f;return{x:(m.d*x-m.c*y)/det,y:(-m.b*x+m.a*y)/det}}
const drawBase0=drawBase;drawBase=function(...args){frameMatrix=snapshotMatrix();return drawBase0(...args)};
function drawFog(){const m=frameMatrix||snapshotMatrix(),ex=explored(),fc=fogCtx,scale=scaleOf(m);fc.setTransform(1,0,0,1,0,0);fc.globalAlpha=1;fc.globalCompositeOperation='source-over';fc.clearRect(0,0,W,H);const corners=[inversePoint(m,0,0),inversePoint(m,W,0),inversePoint(m,0,H),inversePoint(m,W,H)],minX=Math.max(0,Math.min(...corners.map(p=>p.x))),maxX=Math.min(WORLD_W,Math.max(...corners.map(p=>p.x))),minY=Math.max(0,Math.min(...corners.map(p=>p.y))),maxY=Math.min(WORLD_H,Math.max(...corners.map(p=>p.y))),c0=Math.max(0,Math.floor(minX/FOG_CELL)-1),c1=Math.min(FOG_COLS-1,Math.floor(maxX/FOG_CELL)+1),r0=Math.max(0,Math.floor(minY/FOG_CELL)-1),r1=Math.min(FOG_ROWS-1,Math.floor(maxY/FOG_CELL)+1);fc.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);for(let gy=r0;gy<=r1;gy++)for(let gx=c0;gx<=c1;gx++){fc.fillStyle=ex[gy*FOG_COLS+gx]?'rgba(1,7,11,.62)':'rgba(0,1,3,.985)';fc.fillRect(gx*FOG_CELL,gy*FOG_CELL,FOG_CELL+2/scale,FOG_CELL+2/scale)}fc.globalCompositeOperation='destination-out';for(const v of state.v43VisionSources||[]){fc.globalAlpha=.92;fc.fillStyle='#000';fc.beginPath();fc.arc(v.x,v.y,v.r,0,Math.PI*2);fc.fill();fc.globalAlpha=1;fc.beginPath();fc.arc(v.x,v.y,v.r*.84,0,Math.PI*2);fc.fill()}fc.globalAlpha=1;fc.globalCompositeOperation='source-over';fc.setTransform(1,0,0,1,0,0);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(fogCanvas,0,0);ctx.restore()}
const sceneDraw=(typeof v31DrawV32==='function')?v31DrawV32:draw;draw=function(){refreshVision();frameMatrix=null;sceneDraw();drawFog()};
const reset0=reset;reset=function(){reset0();removeBunkers();state.v43FogExplored=new Uint8Array(FOG_COLS*FOG_ROWS);state.v43VisionSources=[];state.v43LegacyCombatError=null;for(const u of state.units||[])delete u.v43RifleCooldowns;installUnitButtons();refreshVision();if(typeof updateHud==='function')updateHud()};if(els?.restart)els.restart.onclick=reset;refreshVision();if(typeof updateHud==='function')updateHud();
})();
