const V47_TITLE='Alien Planet Defense v47';
document.title=V47_TITLE;
window.addEventListener('load',()=>{document.title=V47_TITLE;},{once:true});
(function installV47ConsolidatedRuntime(){
if(window.__apdV47Installed)return;
window.__apdV47Installed=true;
const PERF={HUD_MS:90,ENEMY_GRID:256};
const AIR_ROLES=new Set(['combatdrone','combatship']);
const INFANTRY_ROLES=new Set(['rifleman','heavygunner','rocketeer','medic','engineer','scout','sniper','flametrooper','spotter','minelayer']);
const UNIT_RADII={rifleman:23,heavygunner:24,rocketeer:23,medic:22,engineer:22,scout:21,sniper:21,flametrooper:22,spotter:21,minelayer:23,mech:29,combatdrone:16,combatship:27,tank:29,mobileartillery:28,repairvehicle:27,apc:30,mgcar:24,truck:24};
const UNIT_LABELS={rifleman:'Rifleman Squad',heavygunner:'Heavy Gunner',rocketeer:'Rocketeer Squad',medic:'Medic Squad',engineer:'Engineer Squad',scout:'Scout Squad',sniper:'Sniper Squad',flametrooper:'Flamethrower Troopers',spotter:'Sneaky Spotter Squad',minelayer:'Mine Layer Squad',mech:'Combat Mech',combatdrone:'Combat Drone',combatship:'Combat Ship',tank:'Tank',mobileartillery:'Mobile Artillery',repairvehicle:'Repair Vehicle',apc:'APC',mgcar:'Machinegun Car',truck:'Logistics Truck'};
const roleOf=u=>{try{return typeof unitRole==='function'?unitRole(u):(u?.role||u?.type);}catch{return u?.role||u?.type;}};
const activeUnit=u=>!!u&&(Number(u.hp)||0)>0&&!u.transportedIn&&!u.garrisonedIn;
const cfgForRole=r=>{const direct={rifleman:CONFIG.SOLDIER,heavygunner:CONFIG.HEAVY_GUNNER,rocketeer:CONFIG.ROCKETEER,medic:CONFIG.MEDIC,engineer:CONFIG.ENGINEER,scout:CONFIG.SCOUT,sniper:CONFIG.SNIPER,flametrooper:CONFIG.FLAME_TROOPER,spotter:CONFIG.SPOTTER,minelayer:CONFIG.MINE_LAYER,mech:CONFIG.MECH,combatdrone:CONFIG.COMBAT_DRONE,combatship:CONFIG.COMBAT_SHIP,tank:CONFIG.TANK,mobileartillery:CONFIG.MOBILE_ARTILLERY,repairvehicle:CONFIG.REPAIR_VEHICLE,apc:CONFIG.APC,mgcar:CONFIG.MACHINEGUN_CAR,truck:CONFIG.TRUCK};return direct[r]||CONFIG.SOLDIER;};
function roleCfg(u){try{if(typeof roleConfig==='function'){const c=roleConfig(u);if(c)return c;}}catch{}return cfgForRole(roleOf(u));}
function unitRadiusSafe(u){try{if(typeof uRadius==='function')return Number(uRadius(u))||UNIT_RADII[roleOf(u)]||20;}catch{}return UNIT_RADII[roleOf(u)]||20;}
function isFlying(u){try{return typeof isFlyingUnit==='function'?isFlyingUnit(u):u?.type==='airunit';}catch{return u?.type==='airunit';}}
const sq=x=>x*x;
const dist2=(ax,ay,bx,by)=>{const dx=ax-bx,dy=ay-by;return dx*dx+dy*dy;};
CONFIG.WORLD.MIN_ZOOM=.18;
CONFIG.WORLD.MAX_ZOOM=Math.max(1.35,Number(CONFIG.WORLD.MAX_ZOOM)||1.35);
CONFIG.WORLD.ZOOM_STEP=Number(CONFIG.WORLD.ZOOM_STEP)||.10;
const zoomNow=()=>Math.max(CONFIG.WORLD.MIN_ZOOM,Math.min(CONFIG.WORLD.MAX_ZOOM,Number(state?.camera?.zoom)||1));
function clampCameraV47(){if(!state?.camera)return;const z=zoomNow(),vw=W/z,vh=H/z;state.camera.x=Math.max(0,Math.min(Math.max(0,WORLD_W-vw),Number(state.camera.x)||0));state.camera.y=Math.max(0,Math.min(Math.max(0,WORLD_H-vh),Number(state.camera.y)||0));}
try{clampCamera=clampCameraV47;}catch{}
try{setZoom=function(next,sx=W/2,sy=H/2){const old=zoomNow(),z=Math.max(CONFIG.WORLD.MIN_ZOOM,Math.min(CONFIG.WORLD.MAX_ZOOM,Number(next)||old));const wx=state.camera.x+sx/old,wy=state.camera.y+sy/old;state.camera.zoom=z;state.camera.x=wx-sx/z;state.camera.y=wy-sy/z;clampCameraV47();if(typeof updateZoomLabel==='function')updateZoomLabel();if(typeof updateCancelButtonPosition==='function')updateCancelButtonPosition();return z;};}catch{}
if(typeof makeHorizontalRiver==='function'){try{generateRivers=function(){return[makeHorizontalRiver(WORLD_H*.27+Math.random()*WORLD_H*.035,1),makeHorizontalRiver(WORLD_H*.73+Math.random()*WORLD_H*.035,2)];};}catch{}}
const updateHudBeforeV47=updateHud;
let inSimulationUpdate=false,lastHudAt=-Infinity;
updateHud=function(){const now=performance.now();if(inSimulationUpdate&&now-lastHudAt<PERF.HUD_MS)return;lastHudAt=now;return updateHudBeforeV47();};
function syncBuildLabels(){for(const b of document.querySelectorAll('.buildBtn[data-type]')){const type=b.dataset.type,def=BUILD?.[type],small=b.querySelector('small');if(!def||!small||type==='wall')continue;const cost=Number(def.cost);if(!Number.isFinite(cost))continue;small.textContent=`${cost} ${def.currency==='metal'?'metal':'gold'}`;}}
function removeBunkers(){document.querySelectorAll('.buildBtn[data-type="bunker"]').forEach(b=>b.remove());if(typeof BUILD==='object'&&BUILD)delete BUILD.bunker;const bunkerIds=new Set((state.structures||[]).filter(s=>s.type==='bunker').map(s=>s.id));for(const u of state.units||[]){if(u.garrisonedIn&&bunkerIds.has(u.garrisonedIn)){u.garrisonedIn=null;u.path=[];u.moveTarget=null;}}state.structures=(state.structures||[]).filter(s=>s.type!=='bunker');if(state.selectedTower?.type==='bunker')state.selectedTower=null;if(state.selectedStorageBuilding?.type==='bunker')state.selectedStorageBuilding=null;const gb=document.getElementById('garrisonBtn'),ub=document.getElementById('ungarrisonBtn');if(gb){gb.style.display='none';gb.disabled=true;}if(ub){ub.style.display='none';ub.disabled=true;}for(const box of document.querySelectorAll('#guidePanel .guide-box'))if(/bunker/i.test(box.querySelector('b')?.textContent||''))box.remove();}
const placeBuildBeforeV47=placeBuild;
placeBuild=function(x,y){if(buildType==='bunker'){buildType=null;if(els?.message)els.message.textContent='Bunkers have been removed.';return false;}return placeBuildBeforeV47(x,y);};
function spawnBlocked(x,y,r,air){if(x<r+8||y<r+8||x>WORLD_W-r-8||y>WORLD_H-r-8)return true;if(air)return false;try{if(typeof pointBlockedByTerrain==='function'&&pointBlockedByTerrain(x,y,r*.45))return true;}catch{}try{if(typeof navPointBlocked==='function'&&navPointBlocked(x,y,r*.45))return true;}catch{}for(const s of state.structures||[]){if(!s||s.hp<=0)continue;if(s.type==='wall'&&typeof pointSegmentDistance==='function'&&Number.isFinite(s.x1)){let t=12;try{if(typeof wallThickness==='function')t=Number(wallThickness(s))||12;}catch{}if(pointSegmentDistance(x,y,s.x1,s.y1,s.x2,s.y2)<r+t/2+6)return true;}else if(Number.isFinite(s.x)&&Number.isFinite(s.y)){let sr=30;try{if(typeof structureRadius==='function')sr=Number(structureRadius(s))||30;}catch{}if(dist2(x,y,s.x,s.y)<sq(r+sr+7))return true;}}for(const d of state.depots||[])if(Number.isFinite(d.x)&&dist2(x,y,d.x,d.y)<sq(r+(Number(d.r)||34)+6))return true;for(const u of state.units||[]){if(!activeUnit(u)||!Number.isFinite(u.x))continue;const ur=unitRadiusSafe(u);if(dist2(x,y,u.x,u.y)<sq(r+ur+5))return true;}return false;}
function baseSpawnPoint(role,radius){const air=AIR_ROLES.has(role),r=Math.max(12,Number(radius)||UNIT_RADII[role]||22);if(air){const n=(state.units||[]).filter(u=>activeUnit(u)&&isFlying(u)).length,a=(n*1.73+.35)%(Math.PI*2),d=BASE_RADIUS+r+74+(n%3)*24;return{x:Math.max(r+8,Math.min(WORLD_W-r-8,BASE_X+Math.cos(a)*d)),y:Math.max(r+8,Math.min(WORLD_H-r-8,BASE_Y+Math.sin(a)*d))};}for(let ring=0;ring<15;ring++){const d=BASE_RADIUS+r+48+ring*34;for(let i=0;i<64;i++){const a=i/64*Math.PI*2+ring*.173,x=BASE_X+Math.cos(a)*d,y=BASE_Y+Math.sin(a)*d;if(!spawnBlocked(x,y,r,false))return{x,y};}}return{x:Math.max(r+8,Math.min(WORLD_W-r-8,BASE_X+BASE_RADIUS+r+70)),y:BASE_Y};}
function makeUnitV47(type,p){if(type==='truck'){const hp=(Number(CONFIG.TRUCK.HP)||1)*(Number(state.mods?.truckHp)||1);return{id:'u'+Date.now()+Math.random(),type:'truck',x:p.x,y:p.y,hp,maxHp:hp,moveTarget:null,path:[],heading:0,cargo:0,cargoType:null,route:[],routeIndex:0,routeLoop:false,routeActive:false,routeWaiting:false,routePendingStart:false,platoonId:null,platoonSlot:0};}const role=type==='soldier'?'rifleman':type,air=AIR_ROLES.has(role),cfg=cfgForRole(role)||{};let u=null;try{if(air&&typeof makeAirUnit==='function')u=makeAirUnit(role,p.x,p.y);else if(!air&&typeof makeGroundUnit==='function')u=makeGroundUnit(role,p.x,p.y);}catch(err){console.warn('v47: inherited unit factory failed; using normalized fallback',role,err);}const hp=Math.max(1,Number(cfg.HP)||Number(CONFIG.SOLDIER.HP)||1),members=Math.max(1,Number(cfg.MEMBERS)||Number(cfg.BARRELS)||1);if(!u)u={id:'u'+Date.now()+Math.random(),type:air?'airunit':'soldier',role,x:p.x,y:p.y,hp,maxHp:hp,moveTarget:null,path:[],heading:0,cooldowns:Array.from({length:members},()=>Math.random()*.24)};u.id=u.id||('u'+Date.now()+Math.random());u.type=air?'airunit':'soldier';u.role=role;u.x=p.x;u.y=p.y;u.hp=Number.isFinite(Number(u.hp))?Number(u.hp):hp;u.maxHp=Number.isFinite(Number(u.maxHp))?Number(u.maxHp):hp;u.path=Array.isArray(u.path)?u.path:[];u.moveTarget=u.moveTarget||null;u.heading=Number.isFinite(Number(u.heading))?Number(u.heading):0;u.cooldowns=Array.isArray(u.cooldowns)?u.cooldowns:Array.from({length:members},()=>Math.random()*.24);u.platoonId=null;u.platoonSlot=0;u.garrisonedIn=null;u.transportedIn=null;if(!air){u.attachedTo=null;u.attachSlot=0;}if(role==='medic')u.healFxCooldown=Number(u.healFxCooldown)||0;if(role==='engineer'||role==='repairvehicle')u.repairFxCooldown=Number(u.repairFxCooldown)||0;if(role==='apc')u.passengerId=null;return u;}
function purchaseUnitV47(type){const def=BUILD?.[type];if(!def||def.kind!=='unit')return false;const role=type==='soldier'?'rifleman':type,label=def.label||UNIT_LABELS[role]||type,cost=Math.max(0,Number(def.cost)||Number(cfgForRole(role)?.COST)||0),free=!!state.debug?.unlimitedCash;if(role==='combatship'&&(state.units||[]).some(u=>activeUnit(u)&&roleOf(u)==='combatship')){if(els?.message)els.message.textContent='Only one Combat Ship can be active at a time.';return false;}if(!free&&(Number(state.credits)||0)<cost){if(els?.message)els.message.textContent=`Need ${cost} gold for ${label}.`;updateHud();return false;}if(!free)state.credits-=cost;try{const p=baseSpawnPoint(role,def.radius||UNIT_RADII[role]),u=makeUnitV47(type,p);if(!u||!Number.isFinite(u.x)||!Number.isFinite(u.y)||!Number.isFinite(u.hp)||u.hp<=0)throw new Error('invalid unit object');state.units.push(u);buildType=null;state.routeEditing=false;state.attachMode=false;state.platoonAttachMode=false;state.v47MedicAttachMode=false;state.v47ApcAttachMode=false;state.selectedUnit=u;if('selectedTower'in state)state.selectedTower=null;if('selectedStorageBuilding'in state)state.selectedStorageBuilding=null;if(typeof resetWallPath==='function')try{resetWallPath();}catch{}if(typeof updateTowerPanel==='function')try{updateTowerPanel();}catch{}let name=label;try{if(typeof unitDisplayName==='function')name=unitDisplayName(u)||label;}catch{}if(els?.message)els.message.textContent=`${name} deployed from the base.`;updateHud();return true;}catch(err){if(!free)state.credits+=cost;console.error('v47 unit deployment failed',type,err);if(els?.message)els.message.textContent=`Could not deploy ${label}. Purchase refunded.`;updateHud();return false;}}
function installUnitButtons(){const menu=document.getElementById('unitsMenu');if(!menu)return;for(const old of [...menu.querySelectorAll('.buildBtn[data-type]')]){const type=old.dataset.type,def=BUILD?.[type];if(!def||def.kind!=='unit')continue;const b=old.cloneNode(true);b.type='button';b.disabled=false;b.classList.remove('selected');b.dataset.v47Spawn='authoritative';b.onclick=e=>{e.preventDefault();e.stopPropagation();const ok=purchaseUnitV47(type);if(ok&&typeof closeCommandMenu==='function')setTimeout(()=>{try{closeCommandMenu();}catch{}},0);};b.onpointerdown=e=>e.stopPropagation();b.onpointerup=e=>e.stopPropagation();old.replaceWith(b);}}
try{spawnUnitAtBase=purchaseUnitV47;}catch{}
let enemyGridDirty=true,enemyGrid=new Map();
const gridKey=(x,y)=>`${Math.floor(x/PERF.ENEMY_GRID)},${Math.floor(y/PERF.ENEMY_GRID)}`;
function rebuildEnemyGrid(){enemyGrid=new Map();for(const e of state.enemies||[]){if(!e||e.hp<=0||!Number.isFinite(e.x)||!Number.isFinite(e.y))continue;const k=gridKey(e.x,e.y);let a=enemyGrid.get(k);if(!a)enemyGrid.set(k,a=[]);a.push(e);}enemyGridDirty=false;}
function nearbyEnemies(x,y,r){if(enemyGridDirty)rebuildEnemyGrid();const cs=PERF.ENEMY_GRID,x0=Math.floor((x-r)/cs),x1=Math.floor((x+r)/cs),y0=Math.floor((y-r)/cs),y1=Math.floor((y+r)/cs),out=[];for(let gy=y0;gy<=y1;gy++)for(let gx=x0;gx<=x1;gx++){const a=enemyGrid.get(`${gx},${gy}`);if(a)for(const e of a)if(e.hp>0)out.push(e);}return out;}
function targetableVisible(e,x,y){if(!e||e.hp<=0)return false;try{if(typeof enemyTargetableFrom==='function'&&!enemyTargetableFrom(e,x,y))return false;}catch{}try{if(typeof pointVisibleV32==='function'&&!pointVisibleV32(e.x,e.y))return false;}catch{}return true;}
findTarget=function(x,y,range){const rr=range*range;let best=null,bd=rr;for(const e of nearbyEnemies(x,y,range)){if(!targetableVisible(e,x,y))continue;const d=dist2(x,y,e.x,e.y);if(d<bd){best=e;bd=d;}}return best;};
findTargetWhere=function(x,y,range,predicate,minRange=0){const max2=range*range,min2=minRange*minRange;let best=null,bd=max2;for(const e of nearbyEnemies(x,y,range)){if(!targetableVisible(e,x,y)||!predicate(e))continue;const d=dist2(x,y,e.x,e.y);if(d<=bd&&d>=min2){best=e;bd=d;}}return best;};
nearestTargetsWhere=function(x,y,range,predicate,count,minRange=0){const max2=range*range,min2=minRange*minRange,out=[];for(const e of nearbyEnemies(x,y,range)){if(!targetableVisible(e,x,y)||!predicate(e))continue;const d=dist2(x,y,e.x,e.y);if(d<=max2&&d>=min2)out.push({e,d});}out.sort((a,b)=>a.d-b.d);return out.slice(0,count).map(v=>v.e);};
try{nearestEnemyExcept=function(x,y,range,used){let best=null,bd=range*range;for(const e of nearbyEnemies(x,y,range)){if(used?.has(e)||!targetableVisible(e,x,y))continue;const d=dist2(x,y,e.x,e.y);if(d<bd){best=e;bd=d;}}return best;};}catch{}
try{damageArea=function(x,y,r,damage,predicate=()=>true){const rr=r*r;for(const e of nearbyEnemies(x,y,r))if(e.hp>0&&predicate(e)&&dist2(x,y,e.x,e.y)<=rr)hitEnemy(e,damage);};}catch{}
closestAttackTarget=function(e,maxRange,includeProtected){const max2=maxRange*maxRange;let best=null,bd=max2;for(const s of state.structures||[]){if(!s||s.hp<=0||(!includeProtected&&s.protected))continue;if(!Number.isFinite(s.x)||!Number.isFinite(s.y))continue;const d=dist2(e.x,e.y,s.x,s.y);if(d<bd){best=s;bd=d;}}for(const u of state.units||[]){if(!activeUnit(u)||roleOf(u)==='spotter'||(!includeProtected&&isFlying(u)))continue;const d=dist2(e.x,e.y,u.x,u.y);if(d<bd){best=u;bd=d;}}return best;};
try{saboteurDetected=function(e){const base=Number(CONFIG.SABOTEUR?.REVEAL_RANGE)||145;if(dist2(e.x,e.y,BASE_X,BASE_Y)<=sq(BASE_RADIUS+base))return true;for(const s of state.structures||[])if(s?.built&&s.hp>0&&Number.isFinite(s.x)&&dist2(e.x,e.y,s.x,s.y)<=sq(base))return true;for(const u of state.units||[]){if(!activeUnit(u))continue;const r=roleOf(u),rr=r==='scout'?Math.max(base,Number(CONFIG.SCOUT.DETECT_RANGE)||0):r==='spotter'?Math.max(base,Number(CONFIG.SPOTTER.SPOT_RANGE)||0):base;if(dist2(e.x,e.y,u.x,u.y)<=rr*rr)return true;}return false;};}catch{}
let speedCache=null;
function intrinsicTerrainSpeed(u){let speed;if(u?.type==='truck')speed=Number(CONFIG.TRUCK.MOVE_SPEED)||185;else speed=Number(roleCfg(u)?.MOVE_SPEED)||Number(CONFIG.SOLDIER.MOVE_SPEED)||165;try{if(!isFlying(u)&&typeof pointInRiver==='function'&&pointInRiver(u.x,u.y))speed*=Number(CONFIG.RIVERS?.SLOW_FACTOR)||.5;}catch{}return speed;}
function supportTargets(apc){if(!apc||roleOf(apc)!=='apc'||apc.hp<=0)return[];if(apc.v47SupportPlatoonId&&typeof platoonMembers==='function'){const p=platoonMembers(apc.v47SupportPlatoonId).filter(activeUnit);if(p.length)return p;apc.v47SupportPlatoonId=null;}const u=(state.units||[]).find(v=>v.id===apc.v47SupportUnitId);if(activeUnit(u)&&u!==apc)return[u];apc.v47SupportUnitId=null;return[];}
function supportCenter(apc){const ts=supportTargets(apc);if(!ts.length)return null;let x=0,y=0;for(const u of ts){x+=u.x;y+=u.y;}return{x:x/ts.length,y:y/ts.length,ts};}
function buildMovementCache(){speedCache=new Map();const groupMin=new Map();for(const u of state.units||[]){const s=intrinsicTerrainSpeed(u);speedCache.set(u.id,s);if(u.platoonId&&activeUnit(u)){const p=groupMin.get(u.platoonId);if(p===undefined||s<p)groupMin.set(u.platoonId,s);}}for(const u of state.units||[])if(u.platoonId&&groupMin.has(u.platoonId))speedCache.set(u.id,groupMin.get(u.platoonId));for(const apc of state.units||[]){if(roleOf(apc)!=='apc'||!activeUnit(apc)||apc.passengerId)continue;const c=supportCenter(apc);if(!c||dist2(apc.x,apc.y,c.x,c.y)>360*360)continue;for(const u of c.ts){if(u===apc)continue;const base=speedCache.get(u.id)||intrinsicTerrainSpeed(u),cap=(Number(CONFIG.APC?.MOVE_SPEED)||172)*.94;speedCache.set(u.id,Math.min(cap,base*1.28));}}}
unitSpeed=function(u){if(speedCache?.has(u?.id))return speedCache.get(u.id);return intrinsicTerrainSpeed(u);};
state.v47MedicAttachMode=false;state.v47ApcAttachMode=false;
const medicFollowBtn=document.createElement('button'),medicDetachBtn=document.createElement('button'),apcSupportBtn=document.createElement('button'),apcDetachBtn=document.createElement('button');
medicFollowBtn.textContent='ATTACH / FOLLOW SQUAD';medicDetachBtn.textContent='DETACH FROM SQUAD';apcSupportBtn.textContent='ATTACH / BOOST UNIT';apcDetachBtn.textContent='DETACH SUPPORT';
for(const b of [medicFollowBtn,medicDetachBtn,apcSupportBtn,apcDetachBtn]){b.type='button';b.style.display='none';els.unitActions.appendChild(b);}
const medicFollowTarget=m=>{const t=(state.units||[]).find(u=>u.id===m?.v47FollowId);if(t&&activeUnit(t)&&INFANTRY_ROLES.has(roleOf(t))&&roleOf(t)!=='medic')return t;if(m)m.v47FollowId=null;return null;};
const clearMedic=m=>{if(m){m.v47FollowId=null;m.v47FollowTimer=0;}};
const clearApc=a=>{if(a){a.v47SupportUnitId=null;a.v47SupportPlatoonId=null;a.v47SupportTimer=0;}};
function followPoint(f,t,d){let a=Number(t.heading);if(!Number.isFinite(a))a=Math.atan2(t.y-f.y,t.x-f.x);const r=unitRadiusSafe(f);return{x:Math.max(r+6,Math.min(WORLD_W-r-6,t.x-Math.cos(a)*d)),y:Math.max(r+6,Math.min(WORLD_H-r-6,t.y-Math.sin(a)*d))};}
function apcPassengerSafe(a){try{return typeof apcPassenger==='function'?apcPassenger(a):(a?.passengerId?(state.units||[]).find(u=>u.id===a.passengerId):null);}catch{return null;}}
function attachApc(a,t){if(roleOf(a)!=='apc'||!activeUnit(t)||a===t||apcPassengerSafe(a))return false;try{if(typeof removeFromPlatoon==='function'&&a.platoonId)removeFromPlatoon(a);}catch{}a.v47SupportUnitId=t.id;a.v47SupportPlatoonId=t.platoonId||null;a.path=[];a.moveTarget=null;a.v47SupportTimer=0;return true;}
medicFollowBtn.onclick=()=>{const m=state.selectedUnit;if(roleOf(m)!=='medic')return;state.v47MedicAttachMode=true;state.v47ApcAttachMode=false;state.attachMode=false;state.platoonAttachMode=false;if(els?.message)els.message.textContent='Medic follow mode: tap another infantry squad.';if(typeof closeCommandMenu==='function')closeCommandMenu();};
medicDetachBtn.onclick=()=>{clearMedic(state.selectedUnit);state.v47MedicAttachMode=false;if(els?.message)els.message.textContent='Medic detached.';updateHud();};
apcSupportBtn.onclick=()=>{const a=state.selectedUnit;if(roleOf(a)!=='apc')return;if(apcPassengerSafe(a)){if(els?.message)els.message.textContent='Unload the APC before using support mode.';return;}state.v47ApcAttachMode=true;state.v47MedicAttachMode=false;state.attachMode=false;state.platoonAttachMode=false;if(els?.message)els.message.textContent='APC support mode: tap a unit. A Platoon member boosts the entire Platoon.';if(typeof closeCommandMenu==='function')closeCommandMenu();};
apcDetachBtn.onclick=()=>{clearApc(state.selectedUnit);state.v47ApcAttachMode=false;if(els?.message)els.message.textContent='APC support detached.';updateHud();};
try{if(typeof apcLoadBtn!=='undefined'&&apcLoadBtn){const loadBeforeV47=apcLoadBtn.onclick;apcLoadBtn.onclick=()=>{clearApc(state.selectedUnit);state.v47ApcAttachMode=false;return loadBeforeV47?.();};}}catch{}
const moveBeforeV47=updateUnitMovement;
updateUnitMovement=function(dt){buildMovementCache();moveBeforeV47(dt);for(const m of state.units||[]){if(roleOf(m)!=='medic'||!activeUnit(m))continue;const t=medicFollowTarget(m);if(!t)continue;m.v47FollowTimer=Math.max(0,(m.v47FollowTimer||0)-dt);const p=followPoint(m,t,58),d2=dist2(m.x,m.y,p.x,p.y);if(d2>78*78&&m.v47FollowTimer<=0){setUnitDestination(m,p.x,p.y);m.v47FollowTimer=.42;}else if(d2<34*34&&!t.path?.length){m.path=[];m.moveTarget=null;}}for(const a of state.units||[]){if(roleOf(a)!=='apc'||!activeUnit(a)||apcPassengerSafe(a))continue;const c=supportCenter(a);if(!c)continue;a.v47SupportTimer=Math.max(0,(a.v47SupportTimer||0)-dt);const p=followPoint(a,{x:c.x,y:c.y,heading:c.ts[0]?.heading},110),d2=dist2(a.x,a.y,p.x,p.y);if(d2>145*145&&a.v47SupportTimer<=0){setUnitDestination(a,p.x,p.y);a.v47SupportTimer=.48;}else if(d2<58*58&&c.ts.every(u=>!u.path?.length)){a.path=[];a.moveTarget=null;}}speedCache=null;};
const tapBeforeV47=handleTap;
handleTap=function(x,y){const clicked=unitAt(x,y);if(state.v47MedicAttachMode){const m=state.selectedUnit;if(roleOf(m)!=='medic'){state.v47MedicAttachMode=false;return;}if(!clicked||clicked===m||!activeUnit(clicked)||!INFANTRY_ROLES.has(roleOf(clicked))||roleOf(clicked)==='medic'){if(els?.message)els.message.textContent='Tap another active infantry squad.';return;}try{if(typeof removeFromPlatoon==='function'&&m.platoonId)removeFromPlatoon(m);}catch{}m.attachedTo=null;m.v47FollowId=clicked.id;m.path=[];m.moveTarget=null;state.v47MedicAttachMode=false;if(els?.message)els.message.textContent=`Medic attached to ${unitDisplayName(clicked)}.`;updateHud();return;}if(state.v47ApcAttachMode){const a=state.selectedUnit;if(roleOf(a)!=='apc'){state.v47ApcAttachMode=false;return;}if(!clicked||clicked===a){if(els?.message)els.message.textContent='Tap a movable unit to support.';return;}if(attachApc(a,clicked)){state.v47ApcAttachMode=false;const n=a.v47SupportPlatoonId&&typeof platoonMembers==='function'?platoonMembers(a.v47SupportPlatoonId).length:1;if(els?.message)els.message.textContent=n>1?`APC attached: whole Platoon (${n} units) boosted.`:'APC attached: unit boosted.';updateHud();}return;}const s=state.selectedUnit,tower=typeof towerAt==='function'?towerAt(x,y):null,special=state.attachMode||state.platoonAttachMode||state.routeEditing||(typeof wallModeActive==='function'&&wallModeActive());if(s&&!clicked&&!tower&&!special){if(roleOf(s)==='medic'&&s.v47FollowId)clearMedic(s);if(roleOf(s)==='apc'&&(s.v47SupportUnitId||s.v47SupportPlatoonId))clearApc(s);}return tapBeforeV47(x,y);};
const actionsBeforeV47=updateUnitActions;
updateUnitActions=function(){actionsBeforeV47();const u=state.selectedUnit,r=roleOf(u),m=r==='medic',a=r==='apc',ft=m?medicFollowTarget(u):null,ts=a?supportTargets(u):[];medicFollowBtn.style.display=m&&!ft?'inline-flex':'none';medicDetachBtn.style.display=m&&ft?'inline-flex':'none';if(m){els.attach.style.display='none';els.detach.style.display='none';}apcSupportBtn.style.display=a&&!apcPassengerSafe(u)&&!ts.length?'inline-flex':'none';apcDetachBtn.style.display=a&&ts.length?'inline-flex':'none';const label=document.querySelector('#unitActions .unitActionLabel');if(label&&m&&ft)label.textContent=`MEDIC · FOLLOWING ${unitDisplayName(ft).toUpperCase()}`;if(label&&a&&ts.length)label.textContent=`APC SUPPORT · ${u.v47SupportPlatoonId?'PLATOON '+ts.length+' UNITS':unitDisplayName(ts[0]).toUpperCase()} · +28% MOVE`;const gb=document.getElementById('garrisonBtn'),ub=document.getElementById('ungarrisonBtn');if(gb)gb.style.display='none';if(ub)ub.style.display='none';};
const combatBeforeV47=updateUnitCombat;
function rifleTarget(u){return findTarget(u.x,u.y,Number(CONFIG.SOLDIER.RANGE)||225);}
updateUnitCombat=function(dt){const all=state.units||[],medics=all.filter(u=>roleOf(u)==='medic'&&activeUnit(u)),rifles=all.filter(u=>roleOf(u)==='rifleman'&&activeUnit(u)),removed=new Set([...medics,...rifles]);const savedUnits=state.units;state.units=all.filter(u=>!removed.has(u));try{combatBeforeV47(dt);}catch(err){if(!state.v47CombatError){state.v47CombatError=String(err?.stack||err);console.error('v47 inherited non-rifle combat error',err);}}finally{state.units=savedUnits;}for(const m of medics){if(!state.units.includes(m)||!activeUnit(m))continue;const cfg=CONFIG.MEDIC;let target=null,bestRatio=1,bestD=Infinity;const rr=sq(Number(cfg.HEAL_RANGE)||165);for(const u of state.units){if(u===m||!activeUnit(u)||!INFANTRY_ROLES.has(roleOf(u))||u.hp>=u.maxHp)continue;const d=dist2(m.x,m.y,u.x,u.y);if(d>rr)continue;const ratio=u.hp/u.maxHp;if(ratio<bestRatio||(Math.abs(ratio-bestRatio)<1e-9&&d<bestD)){target=u;bestRatio=ratio;bestD=d;}}if(target){target.hp=Math.min(target.maxHp,target.hp+(Number(cfg.HEAL_PER_SECOND)||11)*dt);m.healFxCooldown=Math.max(0,(m.healFxCooldown||0)-dt);if(m.healFxCooldown<=0&&typeof fxPush==='function'){fxPush({kind:'heal',x1:m.x,y1:m.y,x2:target.x,y2:target.y,expires:performance.now()+150});m.healFxCooldown=.28;}}}for(const u of rifles){if(!state.units.includes(u)||!activeUnit(u))continue;const n=Math.max(1,(Number(CONFIG.SOLDIER.MEMBERS)||6)+(Number(state.mods?.extraSoldiers)||0));if(!Array.isArray(u.v47RifleCooldowns))u.v47RifleCooldowns=Array.from({length:n},()=>Math.random()*.14);while(u.v47RifleCooldowns.length<n)u.v47RifleCooldowns.push(Math.random()*.14);if(u.v47RifleCooldowns.length>n)u.v47RifleCooldowns.length=n;const target=rifleTarget(u);for(let i=0;i<n;i++){u.v47RifleCooldowns[i]=(Number(u.v47RifleCooldowns[i])||0)-dt;if(u.v47RifleCooldowns[i]>0||!target)continue;const off=(typeof SOLDIER_OFFSETS!=='undefined'&&SOLDIER_OFFSETS[i%SOLDIER_OFFSETS.length])||[0,0],x=u.x+off[0],y=u.y+off[1],a=Math.atan2(target.y-y,target.x-x)+(Math.random()-.5)*.018,speed=Number(CONFIG.SOLDIER.BULLET_SPEED)||740,damage=(Number(CONFIG.SOLDIER.DAMAGE)||1.55)*(Number(state.mods?.soldierDamage)||1);state.bullets.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,dmg:damage,life:2.2,type:'soldier'});u.heading=Math.atan2(target.y-u.y,target.x-u.x);u.v47FiringUntil=performance.now()+170;u.v47RifleCooldowns[i]=(Number(CONFIG.SOLDIER.FIRE_INTERVAL)||.5)*(Number(state.mods?.soldierRate)||1)*(.94+Math.random()*.12);}}};
try{v35RiflemanTarget=rifleTarget;}catch{}
updateProjectiles=function(dt){enemyGridDirty=true;rebuildEnemyGrid();for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||!Number.isFinite(b.x)||!Number.isFinite(b.y)){state.bullets.splice(i,1);continue;}let hit=false;for(const e of nearbyEnemies(b.x,b.y,48)){const r=(Number(e.r)||8)+5;if(dist2(b.x,b.y,e.x,e.y)<r*r){hitEnemy(e,b.dmg);hit=true;break;}}if(hit)state.bullets.splice(i,1);}const unitSet=new Set(state.units),structureSet=new Set(state.structures);for(let i=state.enemyBullets.length-1;i>=0;i--){const b=state.enemyBullets[i],t=b.target;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;const valid=t&&(unitSet.has(t)||structureSet.has(t));if(!valid||b.life<=0||roleOf(t)==='spotter'){state.enemyBullets.splice(i,1);continue;}const r=structureOrUnitRadius(t)+5;if(dist2(b.x,b.y,t.x,t.y)<r*r){t.hp-=b.dmg;state.enemyBullets.splice(i,1);}}cleanupDestroyed();enemyGridDirty=true;};
const CACHE={COUNT:6,CAPTURE_R:96,CAPTURE_T:4.5,ACTIVATE_R:620,AGGRO:520,LEASH:680,CONTEST:145,MIN_BASE:760,MAX_BASE:Math.min(2850,Math.min(WORLD_W,WORLD_H)*.38),SEP:760};
function cacheSpotBlocked(x,y){if(dist2(x,y,BASE_X,BASE_Y)<CACHE.MIN_BASE*CACHE.MIN_BASE)return true;try{if(typeof pointBlockedByTerrain==='function'&&pointBlockedByTerrain(x,y,48))return true;}catch{}for(const d of state.depots||[])if(dist2(x,y,d.x,d.y)<sq((d.r||34)+100))return true;for(const s of state.structures||[])if(Number.isFinite(s.x)&&dist2(x,y,s.x,s.y)<150*150)return true;return false;}
function generateCaches(){const out=[];let tries=0;while(out.length<CACHE.COUNT&&tries++<1600){const a=Math.random()*Math.PI*2,d=CACHE.MIN_BASE+Math.random()*(CACHE.MAX_BASE-CACHE.MIN_BASE),x=BASE_X+Math.cos(a)*d,y=BASE_Y+Math.sin(a)*d;if(x<120||y<120||x>WORLD_W-120||y>WORLD_H-120||cacheSpotBlocked(x,y)||out.some(c=>dist2(x,y,c.x,c.y)<CACHE.SEP*CACHE.SEP))continue;out.push({id:`cache-${out.length}-${Math.random().toString(36).slice(2,7)}`,x,y,r:30,capture:0,captured:false,guardsSpawned:false});}return out;}
function rewardForCache(){const fade=Math.max(.35,1-Math.min(1,(state.elapsed||0)/900)*.65);return{gold:Math.round((50+Math.random()*26)*fade),metal:Math.max(1,Math.round((3+Math.random()*3)*fade))};}
function makeGuard(type,box,x,y){let cfg;try{cfg=typeof enemyCfg==='function'?enemyCfg(type):null;}catch{}cfg=cfg||CONFIG.RAVAGER;const level=Math.floor((state.elapsed||0)/60)+1,hp=(Number(cfg.BASE_HP)||6)+level*(Number(cfg.HP_PER_LEVEL)||.5);return{type,x,y,hp,maxHp:hp,speed:((Number(cfg.BASE_SPEED)||65)+level*(Number(cfg.SPEED_PER_LEVEL)||.5))*(Number(CONFIG.DIRECTOR.ENEMY_SPEED_MULTIPLIER)||.3),r:Number(cfg.RADIUS)||7,damage:Number(cfg.BASE_DAMAGE)||2,burn:0,burnTick:0,slowFactor:1,slowTime:0,animOffset:Math.random()*100,rangeCooldown:0,specialCooldown:0,v47GuardBoxId:box.id,v47GuardHomeX:x,v47GuardHomeY:y};}
function guardSpawnPoint(box,index,count){for(let n=0;n<14;n++){const a=index/count*Math.PI*2+n*.47+Math.random()*.25,d=155+Math.random()*70,x=box.x+Math.cos(a)*d,y=box.y+Math.sin(a)*d;if(x<20||y<20||x>WORLD_W-20||y>WORLD_H-20)continue;try{if(typeof navPointBlocked==='function'&&navPointBlocked(x,y,12))continue;}catch{}return{x,y};}return{x:box.x+150,y:box.y};}
function spawnCacheGuards(box){if(box.guardsSpawned||box.captured)return;box.guardsSpawned=true;const types=Math.floor((state.elapsed||0)/60)>=4?['ravager','runner','brute']:['ravager','ravager','runner'];for(let i=0;i<types.length;i++){const p=guardSpawnPoint(box,i,types.length);state.enemies.push(makeGuard(types[i],box,p.x,p.y));}enemyGridDirty=true;if(els?.message)els.message.textContent='Resource cache disturbed — local aliens are defending it.';}
function nearestCacheUnit(box,maxDist,forGuard=false){let best=null,bd=maxDist*maxDist;for(const u of state.units||[]){if(!activeUnit(u)||(forGuard&&roleOf(u)==='spotter'))continue;const d=dist2(u.x,u.y,box.x,box.y);if(d<bd){best=u;bd=d;}}return best;}
function guardBox(e){return(state.v47ResourceCaches||[]).find(b=>b.id===e.v47GuardBoxId);}
function guardBlocked(x,y,r){if(x<r||y<r||x>WORLD_W-r||y>WORLD_H-r)return true;try{if(typeof pointBlockedByTerrain==='function'&&pointBlockedByTerrain(x,y,r*.55))return true;}catch{}try{if(typeof wallAtPointForEnemy==='function'&&wallAtPointForEnemy(x,y,r+1))return true;}catch{}return false;}
function stepGuard(e,tx,ty,speed,dt){const dx=tx-e.x,dy=ty-e.y,d=Math.hypot(dx,dy)||1,step=Math.min(d,speed*dt),base=Math.atan2(dy,dx);for(const off of [0,.48,-.48,.9,-.9,1.35,-1.35]){const a=base+off,nx=e.x+Math.cos(a)*step,ny=e.y+Math.sin(a)*step;if(guardBlocked(nx,ny,e.r))continue;e.x=nx;e.y=ny;return true;}return false;}
function updateGuards(dt,guards){for(const e of guards){if(e.hp<=0)continue;if(e.burn>0){e.burn-=dt;e.burnTick-=dt;if(e.burnTick<=0){try{hitEnemy(e,CONFIG.FLAME.BURN_TICK_DAMAGE*state.mods.flameDamage);}catch{e.hp-=CONFIG.FLAME.BURN_TICK_DAMAGE;}e.burnTick=CONFIG.FLAME.BURN_TICK_INTERVAL;if(e.hp<=0)continue;}}if((e.slowTime||0)>0)e.slowTime=Math.max(0,e.slowTime-dt);else e.slowFactor=1;const box=guardBox(e);if(!box||box.captured){e.hp=0;continue;}const target=nearestCacheUnit(box,CACHE.AGGRO,true),slow=(e.slowTime||0)>0?(e.slowFactor||1):1;let tx=e.v47GuardHomeX,ty=e.v47GuardHomeY;if(target){tx=target.x;ty=target.y;}else if(dist2(e.x,e.y,box.x,box.y)>CACHE.LEASH*CACHE.LEASH){tx=box.x;ty=box.y;}const d2=dist2(tx,ty,e.x,e.y);if(target){const rr=unitRadiusSafe(target),reach=e.r+rr+CONFIG.TOWER_DURABILITY.MELEE_ATTACK_RANGE;if(d2<=reach*reach){target.hp-=e.damage*CONFIG.TOWER_DURABILITY.MELEE_DAMAGE_MULTIPLIER*dt;continue;}}if(d2>100){let speed=e.speed*slow;try{if(typeof pointInRiver==='function'&&pointInRiver(e.x,e.y))speed*=CONFIG.RIVERS.SLOW_FACTOR;}catch{}stepGuard(e,tx,ty,speed,dt);}}}
const enemiesBeforeV47=updateEnemies;
updateEnemies=function(dt){const guards=[],normal=[];for(const e of state.enemies||[])(e.v47GuardBoxId?guards:normal).push(e);state.enemies=normal;enemiesBeforeV47(dt);const survivors=state.enemies;updateGuards(dt,guards);state.enemies=survivors.concat(guards.filter(e=>e.hp>0));enemyGridDirty=true;};
function updateCaches(dt){for(const box of state.v47ResourceCaches||[]){if(box.captured)continue;const activator=nearestCacheUnit(box,CACHE.ACTIVATE_R);if(activator&&!box.guardsSpawned)spawnCacheGuards(box);const unit=nearestCacheUnit(box,CACHE.CAPTURE_R),contested=(state.enemies||[]).some(e=>e.v47GuardBoxId===box.id&&e.hp>0&&dist2(e.x,e.y,box.x,box.y)<=CACHE.CONTEST*CACHE.CONTEST);if(unit&&!contested){box.capture=Math.min(CACHE.CAPTURE_T,box.capture+dt);if(box.capture>=CACHE.CAPTURE_T){box.captured=true;const reward=rewardForCache();if(!state.debug?.unlimitedCash)state.credits=(Number(state.credits)||0)+reward.gold;state.metal=(Number(state.metal)||0)+reward.metal;state.enemies=state.enemies.filter(e=>e.v47GuardBoxId!==box.id);enemyGridDirty=true;if(els?.message)els.message.textContent=`Resource cache secured: +${reward.gold} gold, +${reward.metal} metal.`;updateHud();}}else if(!unit)box.capture=Math.max(0,box.capture-dt*.35);}}
function drawCache(box){if(!worldPointNearView(box.x,box.y,90))return;ctx.save();ctx.translate(box.x,box.y);if(box.captured){ctx.globalAlpha=.35;ctx.fillStyle='#39444a';ctx.fillRect(-25,-18,50,36);ctx.strokeStyle='#75838a';ctx.lineWidth=2;ctx.strokeRect(-25,-18,50,36);ctx.globalAlpha=1;ctx.fillStyle='#a7b3b9';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.fillText('SECURED',0,34);ctx.restore();return;}ctx.fillStyle='#4b3920';ctx.fillRect(-28,-20,56,40);ctx.strokeStyle='#d7ad57';ctx.lineWidth=3;ctx.strokeRect(-28,-20,56,40);ctx.fillStyle='#7a5727';ctx.fillRect(-22,-14,44,9);ctx.fillRect(-22,5,44,9);ctx.fillStyle='#f4cf68';ctx.fillRect(-4,-20,8,40);ctx.fillStyle='rgba(3,9,13,.9)';ctx.fillRect(-34,29,68,15);ctx.strokeStyle='#526d7c';ctx.strokeRect(-34,29,68,15);const pct=Math.round(box.capture/CACHE.CAPTURE_T*100);ctx.fillStyle='#dff7ff';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.fillText(box.capture>0?`CAPTURE ${pct}%`:'RESOURCE CACHE',0,40);if(box.capture>0){ctx.fillStyle='#172229';ctx.fillRect(-29,48,58,5);ctx.fillStyle='#71e09a';ctx.fillRect(-29,48,58*Math.min(1,box.capture/CACHE.CAPTURE_T),5);}ctx.restore();}
const HORDE={FIRST:26,BASE_GAP:48,MIN_GAP:36,GAP_DROP:1.2,START_SIZE:34,SIZE_PER_MIN:6,BASE_MAX:100,MAX_SIZE:220,BATCH:5,BATCH_INTERVAL:.50,START_RADIUS:1500,MAX_RADIUS:2350,RADIUS_GROW:.85,ARC:.62,RADIAL_JITTER:300};
CONFIG.DIRECTOR.ENEMY_SPEED_MULTIPLIER=.30;
if(!window.__v47DirectDamageTuned){window.__v47DirectDamageTuned=true;if(CONFIG.ACID_LOBBER?.SHOT_DAMAGE)CONFIG.ACID_LOBBER.SHOT_DAMAGE*=.70;if(CONFIG.CRUSHER?.CHARGE_DAMAGE)CONFIG.CRUSHER.CHARGE_DAMAGE*=.72;}
function balance(type){if(type==='swarm'||type==='ravager'||type==='runner')return{hp:.58,damage:.55};if(type==='climber'||type==='harvesterhunter')return{hp:.62,damage:.58};if(type==='spitter'||type==='flyer'||type==='burrower'||type==='saboteur')return{hp:.68,damage:.60};if(type==='brute')return{hp:.72,damage:.64};if(type==='acidlobber')return{hp:.76,damage:.66};if(type==='crusher')return{hp:.80,damage:.68};if(type==='siegebeast')return{hp:.86,damage:.72};return{hp:.68,damage:.62};}
function tuneEnemy(e,hordeNo){const b=balance(e.type);e.maxHp=Math.max(1,e.maxHp*b.hp);e.hp=Math.min(e.maxHp,Math.max(1,e.hp*b.hp));e.damage=Math.max(.2,(Number(e.damage)||1)*b.damage);e.v47DamageMult=b.damage;e.v47Horde=true;e.v47HordeNo=hordeNo;}
if(typeof fireEnemyShot==='function'){const shotBeforeV47=fireEnemyShot;fireEnemyShot=function(e,t){const n=state.enemyBullets?.length||0,r=shotBeforeV47(e,t);if(e?.v47DamageMult&&state.enemyBullets?.length>n){const b=state.enemyBullets[state.enemyBullets.length-1];if(b&&Number.isFinite(b.dmg))b.dmg*=e.v47DamageMult;}return r;};}
let threatCache=null,threatCacheAt=-Infinity;
function threatSnapshot(force=false){const now=state.elapsed||0;if(!force&&threatCache&&now-threatCacheAt<1)return threatCache;let units=0,buildings=0,construction=0,walls=0;for(const u of state.units||[])if((Number(u.hp)||0)>0)units++;for(const s of state.structures||[]){if((Number(s.hp)||0)<=0)continue;if(s.type==='wall'){walls++;continue;}if(s.built===false)construction++;else buildings++;}const threat=units+buildings*.9+construction*.55+Math.min(6,walls*.12),sizeMultiplier=1+Math.min(1.35,threat*.032),frequencyMultiplier=1+Math.min(.45,threat*.018);threatCache={units,buildings,construction,walls,threat,sizeMultiplier,frequencyMultiplier};threatCacheAt=now;return threatCache;}
function baseHordeSize(){const m=Math.floor((state.elapsed||0)/60);return Math.min(HORDE.BASE_MAX,HORDE.START_SIZE+m*HORDE.SIZE_PER_MIN);}
function hordeGap(){const m=Math.floor((state.elapsed||0)/60);return Math.max(HORDE.MIN_GAP,HORDE.BASE_GAP-m*HORDE.GAP_DROP);}
function hordeRadius(){return Math.min(HORDE.MAX_RADIUS,HORDE.START_RADIUS+(state.elapsed||0)*HORDE.RADIUS_GROW);}
function hordePoint(e,d){const radius=d.spawnRadius;for(let i=0;i<20;i++){const a=d.angle+(Math.random()-.5)*HORDE.ARC,rr=radius+(Math.random()-.5)*HORDE.RADIAL_JITTER,x=BASE_X+Math.cos(a)*rr,y=BASE_Y+Math.sin(a)*rr,r=(e?.r||8)+8;if(x<r+24||y<r+24||x>WORLD_W-r-24||y>WORLD_H-r-24)continue;try{if(typeof pointBlockedByTerrain==='function'&&pointBlockedByTerrain(x,y,r*.65))continue;}catch{}return{x,y};}return{x:Math.max(30,Math.min(WORLD_W-30,BASE_X+Math.cos(d.angle)*radius)),y:Math.max(30,Math.min(WORLD_H-30,BASE_Y+Math.sin(d.angle)*radius))};}
function spawnHordeEnemy(d){const before=state.enemies.length,sp=CONFIG.SPECIAL_ENEMIES,oldBase=sp?.BASE_CHANCE,oldMax=sp?.MAX_CHANCE,oldFly=CONFIG.FLYER?.SPAWN_CHANCE,oldSpit=CONFIG.RANGED_ALIEN?.SPAWN_CHANCE;if(sp){sp.BASE_CHANCE=Math.min(Number(oldBase)||.08,.05);sp.MAX_CHANCE=Math.min(Number(oldMax)||.36,.18);}if(CONFIG.FLYER)CONFIG.FLYER.SPAWN_CHANCE=Math.min(Number(oldFly)||.10,.06);if(CONFIG.RANGED_ALIEN)CONFIG.RANGED_ALIEN.SPAWN_CHANCE=Math.min(Number(oldSpit)||.03,.035);try{spawnEnemy();}finally{if(sp){sp.BASE_CHANCE=oldBase;sp.MAX_CHANCE=oldMax;}if(CONFIG.FLYER)CONFIG.FLYER.SPAWN_CHANCE=oldFly;if(CONFIG.RANGED_ALIEN)CONFIG.RANGED_ALIEN.SPAWN_CHANCE=oldSpit;}if(state.enemies.length<=before)return;const e=state.enemies[state.enemies.length-1];if(!e||e.v47GuardBoxId)return;const p=hordePoint(e,d);e.x=p.x;e.y=p.y;tuneEnemy(e,d.hordeNo);enemyGridDirty=true;}
function initDirector(){state.v47Director={hordeNo:0,queue:0,batchTimer:0,nextHordeIn:HORDE.FIRST,angle:0,spawnRadius:HORDE.START_RADIUS};state.spawnTimer=999999;threatCache=null;threatCacheAt=-Infinity;}
updateDirector=function(dt){if(!state.v47Director)initDirector();const d=state.v47Director;if(d.queue>0){d.batchTimer-=dt;while(d.queue>0&&d.batchTimer<=0){const n=Math.min(HORDE.BATCH,d.queue);for(let i=0;i<n;i++)spawnHordeEnemy(d);d.queue-=n;d.batchTimer+=HORDE.BATCH_INTERVAL;}if(d.queue<=0)d.nextHordeIn=hordeGap();return;}const scale=d.hordeNo>0?threatSnapshot().frequencyMultiplier:1;d.nextHordeIn-=dt*scale;if(d.nextHordeIn<=0){d.hordeNo++;const t=threatSnapshot(true),base=baseHordeSize();d.queue=Math.min(HORDE.MAX_SIZE,Math.max(base,Math.round(base*t.sizeMultiplier)));d.batchTimer=0;d.angle=Math.random()*Math.PI*2;d.spawnRadius=hordeRadius();d.nextHordeIn=Infinity;d.v47ThreatAtLaunch=t.threat;d.v47UnitsAtLaunch=t.units;d.v47BuildingsAtLaunch=t.buildings+t.construction;state.v47LastThreat=t;}};
const FOG_CELL=96,FOG_COLS=Math.ceil(WORLD_W/FOG_CELL),FOG_ROWS=Math.ceil(WORLD_H/FOG_CELL);
const fogCanvas=document.createElement('canvas');fogCanvas.width=W;fogCanvas.height=H;const fogCtx=fogCanvas.getContext('2d');
let worldMatrix=null;
function snapshotMatrix(){if(typeof ctx.getTransform==='function'){const m=ctx.getTransform();return{a:m.a,b:m.b,c:m.c,d:m.d,e:m.e,f:m.f};}const z=zoomNow();return{a:z,b:0,c:0,d:z,e:-state.camera.x*z,f:-state.camera.y*z};}
function matrixScale(m){return Math.max(.0001,(Math.hypot(m.a,m.b)+Math.hypot(m.c,m.d))/2);}
function inversePoint(m,sx,sy){const det=m.a*m.d-m.b*m.c;if(Math.abs(det)<1e-9)return{x:state.camera.x,y:state.camera.y};const x=sx-m.e,y=sy-m.f;return{x:(m.d*x-m.c*y)/det,y:(-m.b*x+m.a*y)/det};}
function unitVision(u){const r=roleOf(u),cfg=roleCfg(u);if(r==='scout')return 460;if(r==='spotter')return 440;if(r==='sniper')return 520;if(isFlying(u))return 350;return Math.max(250,(Number(cfg?.RANGE)||0)+65,Number(cfg?.DETECT_RANGE)||0,Number(cfg?.SPOT_RANGE)||0);}
function structureVision(s){if(!s?.built||s.hp<=0||s.type==='wall'||s.type==='bunker')return 0;try{if(typeof isUpgradeableTower==='function'&&isUpgradeableTower(s))return Math.max(265,(towerStats(s)?.range||0)+55);}catch{}if(s.type==='landingpad')return 330;if(s.type==='refinery')return 275;if(s.type==='mine'||s.type==='oremine')return 210;return 225;}
let lastExploreMarkAt=-Infinity;
function refreshVision(forceExplore=false){if(!(state.v47FogExplored instanceof Uint8Array)||state.v47FogExplored.length!==FOG_COLS*FOG_ROWS)state.v47FogExplored=new Uint8Array(FOG_COLS*FOG_ROWS);const src=[{x:BASE_X,y:BASE_Y,r:390,kind:'base',id:'base'}];for(const u of state.units||[])if(activeUnit(u))src.push({x:u.x,y:u.y,r:unitVision(u),kind:'unit',id:u.id});for(const s of state.structures||[]){const r=structureVision(s);if(r>0)src.push({x:s.x,y:s.y,r,kind:'structure',id:s.id});}state.v47VisionSources=src;state.v32VisionSources=src;const now=performance.now();if(!forceExplore&&now-lastExploreMarkAt<120)return;lastExploreMarkAt=now;const ex=state.v47FogExplored;for(const v of src){const c0=Math.max(0,Math.floor((v.x-v.r)/FOG_CELL)),c1=Math.min(FOG_COLS-1,Math.floor((v.x+v.r)/FOG_CELL)),r0=Math.max(0,Math.floor((v.y-v.r)/FOG_CELL)),r1=Math.min(FOG_ROWS-1,Math.floor((v.y+v.r)/FOG_CELL)),limit=sq(v.r+FOG_CELL*.72);for(let gy=r0;gy<=r1;gy++)for(let gx=c0;gx<=c1;gx++){const cx=gx*FOG_CELL+FOG_CELL/2,cy=gy*FOG_CELL+FOG_CELL/2;if(dist2(cx,cy,v.x,v.y)<=limit)ex[gy*FOG_COLS+gx]=1;}}}
function pointVisible(x,y){for(const v of state.v47VisionSources||[])if(dist2(x,y,v.x,v.y)<=v.r*v.r)return true;return false;}
try{refreshFogSourcesV32=refreshVision;}catch{}try{pointVisibleV32=pointVisible;}catch{}try{drawFogOverlayV32=function(){};}catch{}
const BASE_IMG=new Image();BASE_IMG.decoding='async';const BASE_SOURCE={w:1536,h:1024},BASE_CROP={x:45,y:1,w:1455,h:976},BASE_WORLD_W=230,BASE_WORLD_H=BASE_WORLD_W*(BASE_CROP.h/BASE_CROP.w);let baseSprite=null,baseReady=false;
function edgeWhite(d,i){const r=d[i],g=d[i+1],b=d[i+2],a=d[i+3];if(a<16)return false;const lo=Math.min(r,g,b),hi=Math.max(r,g,b);return lo>=235&&(hi-lo)<=24;}
function prepareBaseImage(img){const probe=document.createElement('canvas');probe.width=BASE_SOURCE.w;probe.height=BASE_SOURCE.h;const g=probe.getContext('2d',{willReadFrequently:true});g.drawImage(img,0,0,BASE_SOURCE.w,BASE_SOURCE.h);const im=g.getImageData(0,0,BASE_SOURCE.w,BASE_SOURCE.h),d=im.data;let hasAlpha=false;for(let i=3;i<d.length;i+=4)if(d[i]<250){hasAlpha=true;break;}if(hasAlpha)return img;const n=BASE_SOURCE.w*BASE_SOURCE.h,seen=new Uint8Array(n),q=new Int32Array(n);let h=0,t=0;const push=p=>{if(p<0||p>=n||seen[p]||!edgeWhite(d,p*4))return;seen[p]=1;q[t++]=p;};for(let x=0;x<BASE_SOURCE.w;x++){push(x);push((BASE_SOURCE.h-1)*BASE_SOURCE.w+x);}for(let y=1;y<BASE_SOURCE.h-1;y++){push(y*BASE_SOURCE.w);push(y*BASE_SOURCE.w+BASE_SOURCE.w-1);}while(h<t){const p=q[h++],x=p%BASE_SOURCE.w,y=(p/BASE_SOURCE.w)|0;if(x>0)push(p-1);if(x+1<BASE_SOURCE.w)push(p+1);if(y>0)push(p-BASE_SOURCE.w);if(y+1<BASE_SOURCE.h)push(p+BASE_SOURCE.w);}for(let p=0;p<n;p++)if(seen[p])d[p*4+3]=0;g.putImageData(im,0,0);return probe;}
BASE_IMG.onload=()=>{if(BASE_IMG.naturalWidth!==BASE_SOURCE.w||BASE_IMG.naturalHeight!==BASE_SOURCE.h){console.warn('v47: Main Base sprite dimensions differ from expected 1536x1024; procedural fallback retained.');return;}try{baseSprite=prepareBaseImage(BASE_IMG);baseReady=true;window.__apdMainBaseSpriteReady=true;}catch(err){console.error('v47: Main Base sprite preparation failed',err);}};
BASE_IMG.onerror=()=>console.warn('v47: root Main Base PNG not found; procedural fallback retained.');
BASE_IMG.src='A2D31210-1B7B-4D4F-9C2D-0740047D4008.png?v=47';
const drawBaseBeforeV47=drawBase;
drawBase=function(){worldMatrix=snapshotMatrix();if(!baseReady||!baseSprite)return drawBaseBeforeV47();const ratio=Math.max(0,state.baseHp/state.maxBaseHp);ctx.save();ctx.translate(BASE_X,BASE_Y);ctx.imageSmoothingEnabled=true;try{ctx.imageSmoothingQuality='high';}catch{}ctx.drawImage(baseSprite,BASE_CROP.x,BASE_CROP.y,BASE_CROP.w,BASE_CROP.h,-BASE_WORLD_W/2,-BASE_WORLD_H/2,BASE_WORLD_W,BASE_WORLD_H);const bw=178,y=-BASE_WORLD_H/2-31;ctx.fillStyle='rgba(5,11,16,.88)';ctx.fillRect(-bw/2-7,y-20,bw+14,38);ctx.fillStyle='#eaf7ff';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText(state.debug?.unlimitedLives?'BASE ∞ HP':`BASE ${Math.ceil(state.baseHp)} / ${state.maxBaseHp}`,0,y-5);ctx.fillStyle='#111';ctx.fillRect(-bw/2,y+2,bw,10);ctx.fillStyle=ratio>.5?'#59d878':ratio>.25?'#f0c65a':'#ef6666';ctx.fillRect(-bw/2,y+2,bw*(state.debug?.unlimitedLives?1:ratio),10);ctx.restore();};
function drawFog(){const m=worldMatrix||snapshotMatrix(),ex=state.v47FogExplored,fc=fogCtx,scale=matrixScale(m);fc.setTransform(1,0,0,1,0,0);fc.globalAlpha=1;fc.globalCompositeOperation='source-over';fc.clearRect(0,0,W,H);const corners=[inversePoint(m,0,0),inversePoint(m,W,0),inversePoint(m,0,H),inversePoint(m,W,H)],minX=Math.max(0,Math.min(...corners.map(p=>p.x))),maxX=Math.min(WORLD_W,Math.max(...corners.map(p=>p.x))),minY=Math.max(0,Math.min(...corners.map(p=>p.y))),maxY=Math.min(WORLD_H,Math.max(...corners.map(p=>p.y))),c0=Math.max(0,Math.floor(minX/FOG_CELL)-1),c1=Math.min(FOG_COLS-1,Math.floor(maxX/FOG_CELL)+1),r0=Math.max(0,Math.floor(minY/FOG_CELL)-1),r1=Math.min(FOG_ROWS-1,Math.floor(maxY/FOG_CELL)+1);fc.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);fc.fillStyle='rgba(0,1,3,.985)';fc.fillRect(c0*FOG_CELL,r0*FOG_CELL,(c1-c0+1)*FOG_CELL+2/scale,(r1-r0+1)*FOG_CELL+2/scale);fc.fillStyle='rgba(1,7,11,.62)';for(let gy=r0;gy<=r1;gy++){let run=-1;for(let gx=c0;gx<=c1+1;gx++){const explored=gx<=c1&&ex?.[gy*FOG_COLS+gx];if(explored&&run<0)run=gx;else if(!explored&&run>=0){fc.fillRect(run*FOG_CELL,gy*FOG_CELL,(gx-run)*FOG_CELL+2/scale,FOG_CELL+2/scale);run=-1;}}}fc.globalCompositeOperation='destination-out';fc.fillStyle='#000';for(const v of state.v47VisionSources||[]){fc.globalAlpha=.92;fc.beginPath();fc.arc(v.x,v.y,v.r,0,Math.PI*2);fc.fill();fc.globalAlpha=1;fc.beginPath();fc.arc(v.x,v.y,v.r*.84,0,Math.PI*2);fc.fill();}fc.globalAlpha=1;fc.globalCompositeOperation='source-over';fc.setTransform(1,0,0,1,0,0);ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(fogCanvas,0,0);ctx.restore();}
function worldPointNearView(x,y,margin=120){const z=zoomNow(),mx=margin/z;return x>=state.camera.x-mx&&x<=state.camera.x+W/z+mx&&y>=state.camera.y-mx&&y<=state.camera.y+H/z+mx;}
const drawUnitBeforeV47=drawUnit,drawEnemyBeforeV47=drawEnemy,drawStructureBeforeV47=drawStructure,drawDepotBeforeV47=drawDepot,drawBackdropBeforeV47=drawBackdrop;
drawUnit=function(u){if(!u||!worldPointNearView(u.x,u.y,250))return;return drawUnitBeforeV47(u);};
drawEnemy=function(e){if(!e||!worldPointNearView(e.x,e.y,150))return;return drawEnemyBeforeV47(e);};
drawStructure=function(s){if(!s)return;if(s.type==='wall'){const z=zoomNow(),m=720/z,x0=state.camera.x-m,x1=state.camera.x+W/z+m,y0=state.camera.y-m,y1=state.camera.y+H/z+m;if(Math.max(s.x1,s.x2)<x0||Math.min(s.x1,s.x2)>x1||Math.max(s.y1,s.y2)<y0||Math.min(s.y1,s.y2)>y1)return;}else if(!worldPointNearView(s.x,s.y,720))return;return drawStructureBeforeV47(s);};
drawDepot=function(d){if(!worldPointNearView(d.x,d.y,100))return;return drawDepotBeforeV47(d);};
drawBackdrop=function(){drawBackdropBeforeV47();for(const box of state.v47ResourceCaches||[])drawCache(box);};
const indicatorSectors=Array.from({length:12},()=>({count:0,dx:0,dy:0,dist:Infinity}));
drawOffscreenUnitIndicators=function(){if(state.v19Options?.unitArrows===false)return;const z=zoomNow();ctx.save();ctx.setTransform(1,0,0,1,0,0);for(const u of state.units||[]){if(!activeUnit(u))continue;const sx=(u.x-state.camera.x)*z,sy=(u.y-state.camera.y)*z;if(sx>=0&&sx<=W&&sy>=0&&sy<=H)continue;const dx=sx-W/2,dy=sy-H/2,p=edgePoint(dx,dy,28),a=Math.atan2(dy,dx);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle=state.selectedUnit===u?'#ffe47b':u.type==='truck'?'#d2a8ff':isFlying(u)?'#9fe8ff':'#7fe6ff';ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-7,-7);ctx.lineTo(-7,7);ctx.closePath();ctx.fill();ctx.restore();}ctx.restore();};
drawIncomingEnemyArrows=function(){if(state.v19Options?.enemyArrows===false)return;const z=zoomNow();for(const s of indicatorSectors){s.count=0;s.dx=0;s.dy=0;s.dist=Infinity;}for(const e of state.enemies||[]){if(e.hp<=0||!pointVisible(e.x,e.y))continue;const sx=(e.x-state.camera.x)*z,sy=(e.y-state.camera.y)*z;if(sx>=0&&sx<=W&&sy>=0&&sy<=H)continue;const dx=sx-W/2,dy=sy-H/2,a=Math.atan2(dy,dx),idx=(Math.floor(((a+Math.PI)/(Math.PI*2))*12)+12)%12,d=dx*dx+dy*dy,sec=indicatorSectors[idx];sec.count++;if(d<sec.dist){sec.dist=d;sec.dx=dx;sec.dy=dy;}}ctx.save();ctx.setTransform(1,0,0,1,0,0);for(const sec of indicatorSectors){if(!sec.count)continue;const p=edgePoint(sec.dx,sec.dy,36),a=Math.atan2(sec.dy,sec.dx);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle='#ff4f55';ctx.strokeStyle='#450b0d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-8,-9);ctx.lineTo(-4,0);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#fff';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText(sec.count,p.x,p.y+4);}ctx.restore();};
let cleanScene=null;try{if(typeof v31DrawV32==='function')cleanScene=v31DrawV32;}catch{}if(!cleanScene)cleanScene=draw;
function drawScreenOverlays(){ctx.save();ctx.setTransform(1,0,0,1,0,0);if(state.debug?.unlimitedCash||state.debug?.unlimitedLives){ctx.fillStyle='#7fe6ff';ctx.font='bold 13px Arial';ctx.textAlign='left';ctx.fillText(`DEBUG ${state.debug.unlimitedCash?'∞ CASH ':''}${state.debug.unlimitedLives?'∞ LIVES':''}`,14,H-14);}if(state.gameOver){ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='bold 42px Arial';ctx.textAlign='center';ctx.fillText('BASE LOST',W/2,H/2);ctx.font='20px Arial';ctx.fillText('Press RESTART to begin a new run',W/2,H/2+38);}ctx.restore();}
draw=function(){refreshVision();worldMatrix=null;const paused=state.paused,gameOver=state.gameOver,dc=state.debug?.unlimitedCash,dl=state.debug?.unlimitedLives;state.paused=false;state.gameOver=false;if(state.debug){state.debug.unlimitedCash=false;state.debug.unlimitedLives=false;}try{cleanScene();}finally{state.paused=paused;state.gameOver=gameOver;if(state.debug){state.debug.unlimitedCash=dc;state.debug.unlimitedLives=dl;}}drawFog();drawScreenOverlays();};
window.__apdFogOwner='v47-single-overlay';
const updateBeforeV47=update;
update=function(dt){enemyGridDirty=true;inSimulationUpdate=true;try{updateBeforeV47(dt);if(!state.paused&&!state.gameOver&&!state.choosing)updateCaches(dt);}finally{inSimulationUpdate=false;}};
function initializeV47Run(){removeBunkers();if(typeof generateRivers==='function')try{state.rivers=generateRivers();}catch{}state.v47FogExplored=new Uint8Array(FOG_COLS*FOG_ROWS);state.v47VisionSources=[];lastExploreMarkAt=-Infinity;state.v47ResourceCaches=generateCaches();state.v47MedicAttachMode=false;state.v47ApcAttachMode=false;for(const u of state.units||[]){clearMedic(u);clearApc(u);delete u.v47RifleCooldowns;}initDirector();enemyGridDirty=true;speedCache=null;threatCache=null;lastHudAt=-Infinity;clampCameraV47();refreshVision(true);syncBuildLabels();installUnitButtons();if(typeof updateZoomLabel==='function')updateZoomLabel();updateHud();}
const resetBeforeV47=reset;
reset=function(){resetBeforeV47();initializeV47Run();};
if(els?.restart)els.restart.onclick=reset;
initializeV47Run();
if(typeof guideBoxByTitle==='function'){const camera=guideBoxByTitle('Camera');if(camera)camera.querySelector('p').textContent='The battlefield fills the device screen. Use − / + or the mouse wheel to zoom from 18% strategic overview to 135% close view.';const cameraZoom=guideBoxByTitle('Camera Zoom');if(cameraZoom)cameraZoom.querySelector('p').textContent='Use − / + or the mouse wheel to zoom from 18% strategic overview to 135% close view. Zoom stays centered on the chosen screen point.';}
const guide=document.querySelector('#guidePanel .guide-grid');
if(guide){for(const id of ['v37CacheGuide','v38HordeGuide','v39ThreatGuide','v40SupportGuide'])document.getElementById(id)?.remove();const sections=[['v47CacheGuide','Resource Caches','Guarded resource caches are scattered through the exploration ring. Hold a cache after clearing its local defenders to earn a modest Gold/Metal reward. Guards stay local and never march on the Base.'],['v47HordeGuide','Adaptive Enemy Hordes','Aliens arrive in large slow hordes rather than a constant trickle. Horde size and recovery frequency scale with your deployed units and infrastructure, while individual aliens remain tuned for mass-combat pacing.'],['v47SupportGuide','Support Units','Medics heal infantry only and can follow another squad. Sneaky Spotters cannot be attacked. APCs can support one unit or an entire Platoon, giving a +28% movement boost while the APC stays nearby.']];for(const [id,title,text] of sections)if(!document.getElementById(id)){const d=document.createElement('div');d.className='guide-box';d.id=id;d.innerHTML=`<b>${title}</b><p>${text}</p>`;guide.appendChild(d);}}
window.__apdAudit={version:47,consolidated:['v36','v37','v38','v39','v40','v43','v44','v45','v46'],fogOwner:'v47-single-overlay',hudThrottleMs:PERF.HUD_MS,enemyGridCell:PERF.ENEMY_GRID,unitPurchase:'authoritative-all-units',baseSprite:'A2D31210-1B7B-4D4F-9C2D-0740047D4008.png'};
})();
